package oblige.prep;

/**
 *
 * @author felix
 */
public class EarmarkDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewEarMarkDialog
     * @param opesina
     */
    public EarmarkDialog(String opesina) {
        super();
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        javax.swing.InputMap inputMap = getRootPane().getInputMap(javax.swing.JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0), cancelName);
        javax.swing.ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent ae) {
                cancelButtonActionPerformed(ae);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent ae) {
                cancelButtonActionPerformed(null);
            }
        });
        
        OPESINA = opesina;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        javax.swing.JButton cancelButton = new javax.swing.JButton();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tblEarmark = new javax.swing.JTable();

        setTitle("Insert Documents");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        okButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        okButton.setText("Accept");
        okButton.setBorderPainted(false);
        okButton.setEnabled(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setBorderPainted(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.blue);
        jLabel2.setText("Select Earmark and Accept when done to decide on selected item.");

        tblEarmark.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Earmark #", "Expiry", "Amount", "Office", "Sub-Office"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEarmark.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblEarmark);
        if (tblEarmark.getColumnModel().getColumnCount() > 0) {
            tblEarmark.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblEarmark.getColumnModel().getColumn(1).setPreferredWidth(110);
            tblEarmark.getColumnModel().getColumn(2).setPreferredWidth(110);
            tblEarmark.getColumnModel().getColumn(3).setPreferredWidth(150);
            tblEarmark.getColumnModel().getColumn(4).setPreferredWidth(150);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        setSize(new java.awt.Dimension(630, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblEarmark.getModel();
        int selRow = tblEarmark.getSelectedRow();
        selRow = tblEarmark.convertRowIndexToModel(selRow);
        Earmarks = new Object[] {
            modelo.getValueAt(selRow, 0),
            modelo.getValueAt(selRow, 1),
            modelo.getValueAt(selRow, 2),
            modelo.getValueAt(selRow, 3)
        };
        mChoice = true;
        setVisible(false);        
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        mChoice = false;
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String  sqlCmd1 = "SELECT " +
                    "earmark_main.earmrk_id, " +
                    "earmark_main.expiry, " +
                    "earmark_main.total_amnt, " +
                    "fund_control.description, " +
                    "offcies.description " +
                "FROM " +
                    "buds.earmark_main JOIN buds.fund_control " +
                    "ON earmark_main.years = fund_control.years " +
                    "AND earmark_main.resp_cntr = fund_control.centre_uid " +
                    "JOIN buds.fund_control offcies " +
                    "ON SUBSTRING(earmark_main.resp_cntr, 1, 9) = offcies.centre_uid " +
                    "AND earmark_main.years = offcies.years " +
                "WHERE " +
                    "(earmark_main.status = 0) AND " +
                    "(earmark_main.resp_cntr = ?) " +
                "ORDER BY " +
                    "earmark_main.earmrk_id";
//        java.util.Calendar cal = java.util.Calendar.getInstance();
//        cal.setTime(new java.text.SimpleDateFormat("yyyy-MM-dd").parse(System.getProperty("PETSAH"), new java.text.ParsePosition(0)));
        try (budget.DBaseLink jdbc = new budget.DBaseLink();
                java.sql.PreparedStatement psmt1 = jdbc.prepareStatement(sqlCmd1)) {
            
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblEarmark.getModel();
            psmt1.setString(1, OPESINA);
            try (java.sql.ResultSet rst = psmt1.executeQuery()) {
                while (rst.next()) {
                    Object[] rowData = {
                        rst.getString(1),
                        rst.getString(2),
                        rst.getDouble(3),
                        rst.getString(5),
                        rst.getString(4)
                    };
                    modelo.insertRow(modelo.getRowCount(), rowData);
                }
            }
            

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(EarmarkDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {
            tblEarmark.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
                @Override
                public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                    if (evt.getValueIsAdjusting()) return;
                    okButton.setEnabled(tblEarmark.getSelectedRow() >= 0);
                }
            });
        }
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton okButton;
    private javax.swing.JTable tblEarmark;
    // End of variables declaration//GEN-END:variables

    private final String OPESINA;
    
    private Boolean mChoice;
    private Object[] Sources,
                     Earmarks;
    

    public Boolean isChoice() {return mChoice;}
    public Object[] getSources() {return Sources;}
    public Object[] getEarmark() {return Earmarks;}
    
}
