package oblige.prep;

/**
 *
 * @author felix
 */
public class PrepareForm extends javax.swing.JInternalFrame {

//    private final java.util.ArrayList<Short> arDocID = new java.util.ArrayList();
    
    /**
     * Creates new form EarmarkPrepareForm
     */
    public PrepareForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNew = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnClose2 = new javax.swing.JButton();
        pnlOpen = new javax.swing.JPanel();
        btnModify = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        btnElisan = new javax.swing.JButton();
        btnClose3 = new javax.swing.JButton();
        PopupMenu = new javax.swing.JPopupMenu();
        javax.swing.JMenuItem DirectItem = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator2 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem EarmarkItem = new javax.swing.JMenuItem();
        buttonGroup = new javax.swing.ButtonGroup();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        txtTranNo = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        txtBasis = new javax.swing.JTextField();
        txtFund = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        txtResp = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        calTrnDate = new com.toedter.calendar.JDateChooser();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        fmtTotalDoc = new javax.swing.JFormattedTextField();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        optRegular = new javax.swing.JRadioButton();
        optAdjust = new javax.swing.JRadioButton();
        javax.swing.JToolBar jToolBar2 = new javax.swing.JToolBar();
        txtEarmark = new javax.swing.JTextField();
        btnEarmark = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();
        javax.swing.JButton btnOpen = new javax.swing.JButton();
        javax.swing.JButton btnClose = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        tblDocs = new javax.swing.JTable();
        btnAddDoc = new javax.swing.JButton();
        btnDelDoc = new javax.swing.JButton();
        javax.swing.JTabbedPane jTabbedPane1 = new javax.swing.JTabbedPane();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        txtDetail = new javax.swing.JTextArea();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();
        javax.swing.JToolBar jToolBar1 = new javax.swing.JToolBar();
        btnAddFPP = new javax.swing.JButton();
        javax.swing.JToolBar.Separator jSeparator1 = new javax.swing.JToolBar.Separator();
        btnDelFPP = new javax.swing.JButton();
        fmtTotalDet = new javax.swing.JFormattedTextField();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel6 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel7 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        txtReqBy = new javax.swing.JTextField();
        txtDesign = new javax.swing.JTextField();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        calRequest = new com.toedter.calendar.JDateChooser();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        txtPrepBy = new javax.swing.JTextField();
        txtRevwBy = new javax.swing.JTextField();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        txtApprvBy = new javax.swing.JTextField();
        javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
        javax.swing.JCheckBox chkMao1 = new javax.swing.JCheckBox();
        javax.swing.JCheckBox chkMao2 = new javax.swing.JCheckBox();

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/save.png"))); // NOI18N
        btnSave.setText("Post");
        btnSave.setBorderPainted(false);
        btnSave.setEnabled(false);
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setBorderPainted(false);
        btnCancel.setFocusable(false);
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/change.png"))); // NOI18N
        btnChange.setText("Change");
        btnChange.setToolTipText("Change Responsibility Center");
        btnChange.setBorderPainted(false);
        btnChange.setFocusable(false);
        btnChange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChange.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnChange.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectItemActionPerformed(evt);
            }
        });

        btnClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/close.png"))); // NOI18N
        btnClose2.setText("Close");
        btnClose2.setBorderPainted(false);
        btnClose2.setFocusable(false);
        btnClose2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnClose2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNewLayout = new javax.swing.GroupLayout(pnlNew);
        pnlNew.setLayout(pnlNewLayout);
        pnlNewLayout.setHorizontalGroup(
            pnlNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewLayout.createSequentialGroup()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                .addComponent(btnClose2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlNewLayout.setVerticalGroup(
            pnlNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnClose2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/modify.png"))); // NOI18N
        btnModify.setText("Modify");
        btnModify.setBorderPainted(false);
        btnModify.setFocusable(false);
        btnModify.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModify.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnModify.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/back.png"))); // NOI18N
        btnUndo.setText("Back");
        btnUndo.setBorderPainted(false);
        btnUndo.setFocusable(false);
        btnUndo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUndo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnUndo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });

        btnElisan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/change.png"))); // NOI18N
        btnElisan.setText("Change");
        btnElisan.setBorderPainted(false);
        btnElisan.setEnabled(false);
        btnElisan.setFocusable(false);
        btnElisan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnElisan.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnElisan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnClose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/close.png"))); // NOI18N
        btnClose3.setText("Close");
        btnClose3.setBorderPainted(false);
        btnClose3.setFocusable(false);
        btnClose3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnClose3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpenLayout = new javax.swing.GroupLayout(pnlOpen);
        pnlOpen.setLayout(pnlOpenLayout);
        pnlOpenLayout.setHorizontalGroup(
            pnlOpenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpenLayout.createSequentialGroup()
                .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnElisan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(btnClose3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlOpenLayout.setVerticalGroup(
            pnlOpenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModify, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnUndo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnClose3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnElisan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        DirectItem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DirectItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/obligation.png"))); // NOI18N
        DirectItem.setText("Obligation Request");
        DirectItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectItemActionPerformed(evt);
            }
        });
        PopupMenu.add(DirectItem);
        PopupMenu.add(jSeparator2);

        EarmarkItem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        EarmarkItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/earmark.png"))); // NOI18N
        EarmarkItem.setText("From Earmark");
        EarmarkItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EarmarkItemActionPerformed(evt);
            }
        });
        PopupMenu.add(EarmarkItem);

        setClosable(true);
        setIconifiable(true);
        setTitle("Transaction: Obligation - Preparation");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("Transact No.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, -1, -1));

        txtTranNo.setEditable(false);
        txtTranNo.setForeground(java.awt.Color.blue);
        jPanel1.add(txtTranNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 14, 150, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Legal Basis");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 41, -1, -1));

        txtBasis.setEditable(false);
        jPanel1.add(txtBasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 39, 310, -1));

        txtFund.setEditable(false);
        jPanel1.add(txtFund, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 64, 310, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Fund Account");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 66, -1, -1));

        txtResp.setEditable(false);
        jPanel1.add(txtResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 89, 310, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Resp. Center");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 91, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Tran. Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 16, -1, -1));

        calTrnDate.setDateFormatString("MM/dd/yyyy");
        calTrnDate.setEnabled(false);
        jPanel1.add(calTrnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 14, 100, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("Total Amount");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 116, -1, -1));

        lblStatus.setForeground(java.awt.Color.red);
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 14, 250, -1));

        fmtTotalDoc.setEditable(false);
        fmtTotalDoc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        fmtTotalDoc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fmtTotalDoc.setValue(0D);
        jPanel1.add(fmtTotalDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 115, 125, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tran Mode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        buttonGroup.add(optRegular);
        optRegular.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        optRegular.setSelected(true);
        optRegular.setText("Regular");
        optRegular.setEnabled(false);
        optRegular.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup.add(optAdjust);
        optAdjust.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        optAdjust.setText("Adjustment");
        optAdjust.setEnabled(false);
        optAdjust.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optRegular)
                    .addComponent(optAdjust))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(optRegular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(optAdjust)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 110, 60));

        jToolBar2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Earmark", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jToolBar2.setFloatable(false);

        txtEarmark.setEditable(false);
        txtEarmark.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jToolBar2.add(txtEarmark);

        btnEarmark.setText("...");
        btnEarmark.setBorderPainted(false);
        btnEarmark.setEnabled(false);
        btnEarmark.setFocusable(false);
        btnEarmark.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEarmark.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnEarmark.setOpaque(false);
        btnEarmark.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEarmark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EarmarkItemActionPerformed(evt);
            }
        });
        jToolBar2.add(btnEarmark);

        jPanel1.add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 744, 145));

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/open.png"))); // NOI18N
        btnOpen.setText("Open");
        btnOpen.setBorderPainted(false);
        btnOpen.setFocusable(false);
        btnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/close.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.setBorderPainted(false);
        btnClose.setFocusable(false);
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/new.png"))); // NOI18N
        btnNew.setText("NEW");
        btnNew.setBorderPainted(false);
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 486, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnOpen, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 510, 744, 50));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Source Document/s", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDocs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Source", "Doc. No.", "Payee", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDocs.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(tblDocs);
        if (tblDocs.getColumnModel().getColumnCount() > 0) {
            tblDocs.getColumnModel().getColumn(0).setPreferredWidth(170);
            tblDocs.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblDocs.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblDocs.getColumnModel().getColumn(3).setPreferredWidth(120);
            tblDocs.getColumnModel().getColumn(3).setCellRenderer(new tables.DecimalFormatColumnRender(tables.DecimalFormatColumnRender.COMMA_SEPARATED, (short)2, tables.DecimalFormatColumnRender.RIGHT));
        }

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 690, 80));

        btnAddDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/add_row.gif"))); // NOI18N
        btnAddDoc.setToolTipText("Add one Document");
        btnAddDoc.setBorderPainted(false);
        btnAddDoc.setEnabled(false);
        btnAddDoc.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAddDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDocActionPerformed(evt);
            }
        });
        jPanel4.add(btnAddDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        btnDelDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/delete-row.png"))); // NOI18N
        btnDelDoc.setToolTipText("Remove selected Document");
        btnDelDoc.setBorderPainted(false);
        btnDelDoc.setEnabled(false);
        btnDelDoc.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel4.add(btnDelDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 75, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 170, 744, 110));

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtDetail.setEditable(false);
        txtDetail.setColumns(20);
        txtDetail.setRows(3);
        jScrollPane1.setViewportView(txtDetail);

        jTabbedPane1.addTab("Particular", jScrollPane1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FPP", "Account Title", "Acct Code", "Amount", "ppf_id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetail.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblDetail.setEnabled(false);
        tblDetail.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblDetail);
        if (tblDetail.getColumnModel().getColumnCount() > 0) {
            tblDetail.getColumnModel().getColumn(0).setPreferredWidth(200);
            tblDetail.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblDetail.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblDetail.getColumnModel().getColumn(3).setPreferredWidth(120);
            tblDetail.getColumnModel().getColumn(3).setCellRenderer(new tables.DecimalFormatColumnRender(tables.DecimalFormatColumnRender.COMMA_SEPARATED, (short)2, tables.DecimalFormatColumnRender.RIGHT));
            tblDetail.getColumnModel().getColumn(4).setMinWidth(0);
            tblDetail.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblDetail.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnAddFPP.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnAddFPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/add_row.gif"))); // NOI18N
        btnAddFPP.setBorderPainted(false);
        btnAddFPP.setEnabled(false);
        btnAddFPP.setFocusable(false);
        btnAddFPP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddFPP.setOpaque(false);
        btnAddFPP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddFPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFPPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAddFPP);
        jToolBar1.add(jSeparator1);

        btnDelFPP.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnDelFPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/delete-row.png"))); // NOI18N
        btnDelFPP.setBorderPainted(false);
        btnDelFPP.setEnabled(false);
        btnDelFPP.setFocusable(false);
        btnDelFPP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelFPP.setOpaque(false);
        btnDelFPP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelFPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelFPPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDelFPP);

        fmtTotalDet.setEditable(false);
        fmtTotalDet.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        fmtTotalDet.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fmtTotalDet.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        fmtTotalDet.setValue(0D);

        jLabel9.setText("Total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fmtTotalDet, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fmtTotalDet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Details", jPanel2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Linkages", jPanel5);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true)));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Requested by");

        txtReqBy.setEditable(false);
        txtReqBy.setDocument(new dbase.dcare.FixedSizePlainDocument(60));

        txtDesign.setEditable(false);
        txtDesign.setDocument(new dbase.dcare.FixedSizePlainDocument(30));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setText("Designation");

        calRequest.setDateFormatString("MM/dd/yyyy");
        calRequest.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setText("Date");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtReqBy)
                    .addComponent(txtDesign))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtReqBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(calRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("Prepared by");

        txtPrepBy.setEditable(false);

        txtRevwBy.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel14.setText("Reviewed by");

        txtApprvBy.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel15.setText("Approved by");

        chkMao1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkMao1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chkMao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMao1ActionPerformed(evt);
            }
        });

        chkMao2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkMao2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrepBy, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRevwBy, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkMao1))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApprvBy, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkMao2)))
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtPrepBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRevwBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(chkMao1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApprvBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addComponent(chkMao2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Signatory Officers", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 290, 744, 210));

        setBounds(0, 0, 780, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        getContentPane().add(pnlNew,  new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 510, 744, 50));
        getContentPane().add(pnlOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 510, 744, 50));
        pnlNew.setVisible(false);
        pnlOpen.setVisible(false);
        
        txtPrepBy.setText(System.getProperty("USERNAME"));
        tblDetail.getModel().addTableModelListener(new javax.swing.event.TableModelListener() {
            @Override
            public void tableChanged(javax.swing.event.TableModelEvent evt) {
                if (evt.getType() != javax.swing.event.TableModelEvent.INSERT) return;
                
                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblDetail.getModel();
                double total = 0D;
                for (short abc = 0; abc < modelo.getRowCount(); abc++) {
                    total += Double.parseDouble(modelo.getValueAt(abc, 3).toString());
                }
                fmtTotalDet.setValue(total);
            }
        });
        tblDetail.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                if (evt.getValueIsAdjusting()) return;
                btnDelFPP.setEnabled(tblDetail.getSelectedRow() >= 0 & btnAddFPP.isEnabled());
            }
        });
//        btnNew.addActionListener(new java.awt.event.ActionListener() {
//            @Override
//            public void actionPerformed(java.awt.event.ActionEvent ev) {
//                if (btnNew.isSelected())
//                    PopupMenu.show(btnNew, 0, btnNew.getBounds().height);
//                else
//                    btnNew.setVisible(false);
//            }
//        });
//        PopupMenu.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
//            @Override
//            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent e) {}
//            @Override
//            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent e) {btnNew.setSelected(false);}
//            @Override
//            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent e) {}
//        });
        tblDocs.getModel().addTableModelListener(new javax.swing.event.TableModelListener() {
            @Override
            public void tableChanged(javax.swing.event.TableModelEvent evt) {
                if (evt.getType() != javax.swing.event.TableModelEvent.INSERT) return;
                
                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblDocs.getModel();
                double total = 0D;
                for (short abc = 0; abc < modelo.getRowCount(); abc++) {
                    total += Double.parseDouble(modelo.getValueAt(abc, 3).toString());
                }
                fmtTotalDoc.setValue(total);
            }
        });
        tblDocs.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                if (evt.getValueIsAdjusting()) return;
                btnDelDoc.setEnabled(tblDocs.getSelectedRow() >= 0);
                btnSave.setEnabled(tblDocs.getSelectedRow() >= 0);
            }
        });
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        LegalBasis = null;
        Fund = null;
        Office = null;

        calTrnDate.setDate(null);
        txtTranNo.setText("");
        txtBasis.setText("");
        txtFund.setText("");
        txtDetail.setText("");
        txtResp.setText("");
        txtReqBy.setText("");
        txtDesign.setText("");
        calRequest.setDate(null);
        fmtTotalDet.setValue(0D);
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblDetail.getModel();
        modelo.setRowCount(0);
        modelo = (javax.swing.table.DefaultTableModel)tblDocs.getModel();
        modelo.setRowCount(0);
        lblStatus.setText("");
        txtEarmark.setText("");
        CLASS_CODE = "";



        boolean turnOff = false;
        pnlNew.setVisible(turnOff);
        pnlMain.setVisible(!turnOff);
        calTrnDate.setEnabled(turnOff);
        btnAddFPP.setEnabled(turnOff);
        tblDetail.setEnabled(turnOff);
        txtDetail.setEditable(turnOff);
        txtReqBy.setEditable(turnOff);
        txtDesign.setEditable(turnOff);
        calRequest.setEnabled(turnOff);
        optRegular.setEnabled(turnOff);
        optAdjust.setEnabled(turnOff);
        btnAddDoc.setEnabled(turnOff);

        pnlNew.setVisible(turnOff);
        pnlMain.setVisible(!turnOff);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddFPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFPPActionPerformed
        // TODO add your handling code here:
        earmark.prep.AddFPPDialog dialogo = new earmark.prep.AddFPPDialog(Office, CLASS_CODE);
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
        
        if (!dialogo.isChoice()) {
            dialogo.dispose();
            return;
        }
        
        try {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblDetail.getModel();
            earmark.Classification leafNode = dialogo.getNapiliNode();
            Object[] rowData = {
                dialogo.getPPF()[1],
                leafNode.getTitulo(),
                leafNode.getUID(),
                0D,
                leafNode.getBalances(),
                dialogo.getPPF()[0]
            };
            modelo.addRow(rowData);
            CLASS_CODE = leafNode.getRootID();
            java.util.Calendar caldate = java.util.Calendar.getInstance();
            caldate.setTime(new java.text.SimpleDateFormat("yyyy-MM-dd").parse(System.getProperty("PETSAH")));
            txtTranNo.setText(CLASS_CODE + "-" + caldate.get(java.util.Calendar.YEAR) + "-######");

            btnSave.setEnabled(true);

        
        } catch (java.text.ParseException | NumberFormatException mex) {
            javax.swing.JOptionPane.showMessageDialog(this, mex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, mex);
        } finally {
            
        }
    }//GEN-LAST:event_btnAddFPPActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        doDefaultCloseAction();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String sqlCmd0 =
                "INSERT INTO buds.obligate_main (" +
                    "trans_no, " +      // 1 - character
                    "years, " +         // 2 - smallint
                    "transact, " +      // 3 - date
                    "modes, " +         // 4 - smallint
                    "legal_uid, " +     // 5 - integer
                    "fund_acct, " +     // 6 - smallint
                    "resp_cntr, " +     // 7 - character
                    "earmrk_id, " +     // 8 - character
                    "obligated, " +     // 9 - double precision
                    "particular, " +    //10 - character
                    "req_date, " +      //11 - date
                    "requested, " +     //12 - character
                    "posisyon, " +      //13 - character
                    "prepared, " +      //14 - character
                    "reviewed, " +      //15 - character
                    "approved, " +      //16 - character
                    "userid) " +        //17 - character
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
               sqlCmd1 = 
                "INSERT INTO buds.obligate_doc (" +
                    "trans_no, " +  // 1 - character
                    "alobs_id) " +  // 2 - character
                "VALUES(?, ?)",
               sqlCmd2 = 
                "INSERT INTO buds.obligate_fpp (" +
                    "trans_no, " +  // 1 - character
                    "seq_order, " + // 2 - smallint
                    "ppf_uid, " +   // 3 - character
                    "acct_code, " + // 4 - character
                    "amount, " +    // 5 - double
                    "classes) " +   // 6 - smallint
                "VALUES(?, ?, ?, ?, ?, ?)";
        
        
        try (budget.DBaseLink jdbc = new budget.DBaseLink();
                java.sql.PreparedStatement serial = jdbc.prepareStatement("SELECT NEXTVAL('buds.earmark_seq');")) {
            
            java.util.Calendar caldate = java.util.Calendar.getInstance();
            caldate.setTime(new java.text.SimpleDateFormat("yyyy-MM-dd").parse(System.getProperty("PETSAH")));
            short year = (short)caldate.get(java.util.Calendar.YEAR);
            
            String ObligeNo = txtTranNo.getText();
            try(java.sql.PreparedStatement psmt0 = jdbc.prepareStatement(sqlCmd0);
                    java.sql.PreparedStatement psmt1 = jdbc.prepareStatement(sqlCmd1);
                    java.sql.PreparedStatement psmt2 = jdbc.prepareStatement(sqlCmd2)) {
                jdbc.setAutoCommit(false);
                
                psmt0.setString(1,  ObligeNo);
                psmt0.setShort (2,  year);
                psmt0.setDate  (3,  new java.sql.Date(calTrnDate.getDate().getTime()));
                psmt0.setShort (4,  (short)(optRegular.isSelected() ? 1 : 2));
                psmt0.setInt   (5,  LegalBasis);
                psmt0.setShort (6,  Fund);
                psmt0.setString(7,  Office);
                psmt0.setString(8,  txtEarmark.getText());
                psmt0.setDouble(9,  Double.parseDouble(fmtTotalDoc.getValue().toString()));
                psmt0.setString(10, txtDetail.getText());
                psmt0.setDate  (11, new java.sql.Date(calRequest.getDate().getTime()));
                psmt0.setString(12, txtReqBy.getText());
                psmt0.setString(13, txtDesign.getText());
                psmt0.setString(14, txtPrepBy.getText());
                psmt0.setString(15, txtRevwBy.getText());
                psmt0.setString(16, txtApprvBy.getText());
                psmt0.setString(17, System.getProperty("USERID"));
                psmt0.executeUpdate();
                
                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblDocs.getModel();
                for (short abc = 0; abc < modelo.getRowCount(); abc++) {
                    psmt1.setString(1, ObligeNo);
                    psmt1.setString(2, OBLIGE_NO);
                    psmt1.addBatch();
                }
                psmt1.executeBatch();

                modelo = (javax.swing.table.DefaultTableModel)tblDetail.getModel();
                for (short abc = 0; abc < modelo.getRowCount(); abc++) {
                    psmt2.setString(1,  ObligeNo);
                    psmt2.setShort (2,  (short)(abc + 1));
                    psmt2.setString(3,  modelo.getValueAt(abc, 4).toString());
                    psmt2.setString(4,  modelo.getValueAt(abc, 2).toString());
                    long value = Math.round(((Double)modelo.getValueAt(abc, 3)) * 100D);
                    psmt2.setDouble(5,  value * 0.01D);
                    psmt2.setShort (6,  Short.parseShort(CLASS_CODE, 10));
                    psmt2.addBatch();
                }
                psmt1.executeBatch();
                jdbc.commit();
                
                if (lblStatus.getText().isEmpty()) lblStatus.setText("For Approval");

                javax.swing.JOptionPane.showMessageDialog(this, "Record saved successfully.", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);
                pnlNew.setVisible(false);
                pnlMain.setVisible(true);


            } catch (java.sql.SQLException ex) {
                jdbc.rollback();
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDelFPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelFPPActionPerformed
        // TODO add your handling code here:
        int selrow = tblDetail.getSelectedRow(), rowIhap = tblDetail.getRowCount();
        
        btnDelFPP.setEnabled(rowIhap > 0);
        selrow = tblDetail.convertRowIndexToModel(selrow);

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblDetail.getModel();
        String sqlCmdM =
                "DELETE FROM " +
                    "buds.earmark_main " +
                "WHERE " +
                    "(earmrk_id = ?)",
               sqlCmdS = 
                "DELETE FROM " +
                    "buds.earmark_sub " +
                "WHERE " +
                    "(earmrk_id = ?) AND " +
                    "(ppf_uid   = ?) AND " +
                    "(acct_code = ?)",
               earMark = txtTranNo.getText(),
               accnts  = modelo.getValueAt(selrow, 2).toString(),
               ppfIDs  = modelo.getValueAt(selrow, 4).toString();
        try (budget.DBaseLink jdbc = new budget.DBaseLink();
                java.sql.PreparedStatement psmtm = jdbc.prepareStatement(sqlCmdM);
                java.sql.PreparedStatement psmts = jdbc.prepareStatement(sqlCmdS)) {
            jdbc.setAutoCommit(false);
            try {
                psmts.setString(1, earMark);
                psmts.setString(2, ppfIDs);
                psmts.setString(3, accnts);
                psmts.executeUpdate();

                psmtm.setString(1, earMark);
                if (rowIhap == 1) psmtm.executeUpdate();
                jdbc.commit();

                modelo.removeRow(selrow);
                javax.swing.JOptionPane.showMessageDialog(this, "Record remove successfully.", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);


            } catch (java.sql.SQLException ex) {
                jdbc.rollback();
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_btnDelFPPActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        earmark.prep.OpenDialog dialogo = new earmark.prep.OpenDialog();
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
        
        if (!dialogo.isChoice()) return;

        txtTranNo.setText(dialogo.getEarMark());
        otrogQuery();
        
        btnModify.setEnabled(lblStatus.getText().equals("For Approval"));
        pnlOpen.setVisible(true);
        pnlMain.setVisible(false);
    }//GEN-LAST:event_btnOpenActionPerformed

    private void otrogQuery() {
        String sqlCmdM =
                "SELECT " +
                    "earmark_main.transact, " +     // 1
                    "earmark_main.expiry, " +       // 2
                    "earmark_main.legal_uid, " +    // 3
                    "ordinances.legal_desc, " +     // 4
                    "earmark_main.fund_acct, " +    // 5
                    "funds.description, " +         // 6
                    "earmark_main.resp_cntr, " +    // 7
                    "offices.resp_id, " +           // 8
                    "offices.resp_sub, " +          // 9
                    "offices.description, " +       //10
                    "earmark_main.particular, " +   //11
                    "earmark_main.requested, " +    //12
                    "earmark_main.total_amnt, " +   //13
                    "earmark_main.status " +        //14
                "FROM " +
                    "buds.earmark_main JOIN buds.ordinances " +
                    "ON earmark_main.legal_uid = ordinances.legal_uid " +
                    "JOIN buds.fund_control funds " +
                    "ON earmark_main.years = funds.years " +
                    "AND earmark_main.fund_acct = funds.funds_id " +
                    "JOIN buds.fund_control offices " +
                    "ON earmark_main.years = offices.years " +
                    "AND earmark_main.resp_cntr = offices.centre_uid " +
                "WHERE " +
                    "(earmark_main.earmrk_id = ?) AND " +
                    "(funds.funds_id <> 0) AND (funds.services = 0)",
               sqlCmdS = 
                "SELECT " +
                    "fund_control.description, " +      // 1
                    "accounts.titles, " +               // 2
                    "accounts.coding, " +               // 3
                    "earmark_sub.amount, " +            // 4
                    "earmark_sub.allot_bal, " +         // 5
                    "earmark_sub.ppf_uid " +            // 6
                "FROM " +
                    "buds.earmark_sub JOIN buds.fund_control " +
                    "ON earmark_sub.years = fund_control.years " +
                    "AND earmark_sub.ppf_uid = fund_control.centre_uid " +
                    "JOIN acct.accounts " +
                    "ON earmark_sub.acct_code = accounts.coding " +
                "WHERE " +
                    "(earmark_sub.earmrk_id = ?) " +
                "ORDER BY " +
                    "earmark_sub.seq_order",
               earMark = txtTranNo.getText();
        try (budget.DBaseLink jdbc = new budget.DBaseLink();
                java.sql.PreparedStatement psmtm = jdbc.prepareStatement(sqlCmdM);
                java.sql.PreparedStatement psmts = jdbc.prepareStatement(sqlCmdS)) {
            
            psmtm.setString(1, earMark);
            try (java.sql.ResultSet rst = psmtm.executeQuery()) {
                rst.next();
                calTrnDate.setDate(rst.getDate(1));
                LegalBasis = rst.getInt(3);
                txtBasis.setText(rst.getString(4));
                Fund = rst.getShort(5);
                txtFund.setText(rst.getShort(5) + " - " + rst.getString(6));
                Office = rst.getString(7);
                txtResp.setText(rst.getShort(8) + "-" + rst.getShort(9) + " " + rst.getString(10));
                txtDetail.setText(rst.getString(11));
                txtReqBy.setText(rst.getString(12));
                fmtTotalDet.setValue(rst.getDouble(13));
                lblStatus.setText((rst.getShort(14) == 0 ? "For Approval" : rst.getShort(14) == 1 ? "Approved" : rst.getShort(14) == 2 ? "Cancelled" : "Unknown"));
                //javax.swing.JOptionPane.showMessageDialog(this, "Record remove successfully.", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            psmts.setString(1, earMark);
            try (java.sql.ResultSet tbl = psmts.executeQuery()) {
                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblDetail.getModel();
                modelo.setRowCount(0);
                while (tbl.next()) {
                    Object[] rowData = {
                        tbl.getString(1),
                        tbl.getString(2),
                        tbl.getString(3),
                        tbl.getDouble(4),
                        tbl.getDouble(5),
                        tbl.getString(6)
                    };
                    modelo.addRow(rowData);
                }
            }


        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }
    
    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        boolean switchOn = evt.getActionCommand().equals("Modify");
        calTrnDate.setEnabled(switchOn);
        txtDetail.setEditable(switchOn);
        txtReqBy.setEditable(switchOn);
        btnAddFPP.setEnabled(switchOn);
        optRegular.setEnabled(switchOn);
        optAdjust.setEnabled(switchOn);
        tblDetail.setEnabled(switchOn);
        btnUndo.setEnabled(switchOn);
        btnElisan.setEnabled(switchOn);

        if (switchOn) {
            btnModify.setText("Update");
            btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/update.png"))); // NOI18N
            btnUndo.setText("Undo");
            btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/undo.png"))); // NOI18N
        } else {
            UpdateEarmark();
            btnModify.setText("Modify");
            btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/modify.png"))); // NOI18N
            btnUndo.setText("Back");
            btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/back.png"))); // NOI18N
        }
    }//GEN-LAST:event_btnModifyActionPerformed
    
    private void UpdateEarmark() {
        String
            sqlCmdM =
                "UPDATE " +
                    "buds.earmark_main " +
                "SET " +
                    "transact   = ?, " + // 1 - date
                    "expiry     = ?, " + // 2 - date
                    "legal_uid  = ?, " + // 3 - integer
                    "fund_acct  = ?, " + // 4 - smallint
                    "resp_cntr  = ?, " + // 5 - character
                    "particular = ?, " + // 6 - character
                    "requested  = ?, " + // 7 - character
                    "total_amnt = ?, " + // 8 - double
                    "userid     = ?  " + // 9 - character
                "WHERE " +
                    "(earmrk_id = ?)",   //10
            sqlCmdS = 
                "UPDATE " +
                    "buds.earmark_sub " +
                "SET " +
                    "seq_order = ?, " +         // 1 - smallint
                    "amount    = ?, " +         // 2 - double
                    "allot_bal = ? " +          // 3 - double
                "WHERE " +
                    "(earmrk_id = ?) AND " +    // 4
                    "(ppf_uid   = ?) AND " +    // 5
                    "(acct_code = ?)",          // 6
            sqlCmdI = 
                "INSERT INTO buds.earmark_sub (" +
                    "years, " +         // 1
                    "earmrk_id, " +     // 2
                    "seq_order, " +     // 3
                    "ppf_uid, " +       // 4
                    "acct_code, " +     // 5
                    "amount, " +        // 6
                    "allot_bal) " +     // 7
                "VALUES " +
                    "(?, ?, ?, ?, ?, ?, ?)";
        try (budget.DBaseLink jdbc = new budget.DBaseLink();
                java.sql.PreparedStatement serial = jdbc.prepareStatement("SELECT NEXTVAL('buds.earmark_seq');")) {
            String newEarmark = txtTranNo.getText();
            java.util.Calendar caldate = java.util.Calendar.getInstance();
            caldate.setTime(new java.text.SimpleDateFormat("yyyy-MM-dd").parse(System.getProperty("PETSAH")));
            short year = (short)caldate.get(java.util.Calendar.YEAR);

            try(java.sql.PreparedStatement pstm = jdbc.prepareStatement(sqlCmdM);
                    java.sql.PreparedStatement psts = jdbc.prepareStatement(sqlCmdS);
                    java.sql.PreparedStatement psti = jdbc.prepareStatement(sqlCmdI)) {
                jdbc.setAutoCommit(false);
                pstm.setDate  ( 1,  new java.sql.Date(calTrnDate.getDate().getTime()));
                pstm.setInt   ( 3,  LegalBasis);
                pstm.setShort ( 4,  Fund);
                pstm.setString( 5,  Office);
                pstm.setString( 6,  txtDetail.getText());
                pstm.setString( 7,  txtReqBy.getText());
                pstm.setDouble( 8,  Double.parseDouble(fmtTotalDet.getValue().toString()));
                pstm.setString( 9,  System.getProperty("USERID"));
                /***************************************************************/
                pstm.setString(10, newEarmark);
                pstm.executeUpdate();
                
                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblDetail.getModel();
                for (short abc = 0; abc < modelo.getRowCount(); abc++) {
                    psts.setShort (1,  (short)(abc + 1));
                    long value = Math.round(((Double)modelo.getValueAt(abc, 3)) * 100D);
                    psts.setDouble(2,  value * 0.01D);
                    value = Math.round(((Double)modelo.getValueAt(abc, 4)) * 100D);
                    psts.setDouble(3,  value * 0.01D);
                    /***********************************************************/
                    psts.setString(4,  newEarmark);
                    psts.setString(5,  modelo.getValueAt(abc, 5).toString());
                    psts.setString(6,  modelo.getValueAt(abc, 2).toString());
                    if (psts.executeUpdate() == 0) {
                        psti.setShort (1, year);
                        psti.setString(2, newEarmark);
                        psti.setShort (3, (short)(abc + 1));
                        psti.setString(4, modelo.getValueAt(abc, 5).toString());
                        psti.setString(5, modelo.getValueAt(abc, 2).toString());
                        value = Math.round(((Double)modelo.getValueAt(abc, 3)) * 100D);
                        psti.setDouble(6,  value * 0.01D);
                        value = Math.round(((Double)modelo.getValueAt(abc, 4)) * 100D);
                        psti.setDouble(7,  value * 0.01D);
                        psti.executeUpdate();
                    }
                }
                jdbc.commit();
                
                if (lblStatus.getText().isEmpty()) lblStatus.setText("For Approval");

                javax.swing.JOptionPane.showMessageDialog(this, "Record saved successfully.", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);
                pnlOpen.setVisible(false);
                pnlMain.setVisible(true);


            } catch (java.sql.SQLException ex) {
                jdbc.rollback();
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        // TODO add your handling code here:
        boolean switchOn = evt.getActionCommand().equals("Undo");
        if (switchOn) {
            btnUndo.setText("Back");
            btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/back.png"))); // NOI18N
            btnModify.setText("Modify");
            btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/modify.png"))); // NOI18N

        } else {
            calTrnDate.setDate(null);

            LegalBasis = null;
            Fund = null;
            Office = null;

            txtTranNo.setText("");
            txtBasis.setText("");
            txtFund.setText("");
            txtDetail.setText("");
            txtResp.setText("");
            txtReqBy.setText("");
            fmtTotalDet.setValue(0D);


            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblDetail.getModel();
            modelo.setRowCount(0);
            lblStatus.setText("");
            
            pnlNew.setVisible(false);
            pnlOpen.setVisible(false);
            pnlMain.setVisible(true);
        }
        calTrnDate.setEnabled(switchOn);
        txtDetail.setEditable(switchOn);
        txtReqBy.setEditable(switchOn);
        btnAddFPP.setEnabled(switchOn);
        //btnDelFPP.setEnabled(switchOn);
        tblDetail.setEnabled(switchOn);
        btnElisan.setEnabled(switchOn);
    }//GEN-LAST:event_btnUndoActionPerformed

    private void DirectItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectItemActionPerformed
        // TODO add your handling code here:
        earmark.prep.TransDialog dialogo = new earmark.prep.TransDialog();
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);

        if (!dialogo.isChoice()) {
            dialogo.dispose();
            return;
        }
        try {
            earmark.Opesina selNode = dialogo.getNapiliNode();
            java.util.Calendar caldate = java.util.Calendar.getInstance();
            caldate.setTime(new java.text.SimpleDateFormat("yyyy-MM-dd").parse(System.getProperty("PETSAH")));
            String bulan = new java.text.DecimalFormat("00").format(caldate.get(java.util.Calendar.MONTH) + 1);
            txtTranNo.setText(caldate.get(java.util.Calendar.YEAR) + "-" + bulan + "-######");
            calTrnDate.setDate(caldate.getTime());
            caldate.add(java.util.Calendar.DATE, 5);
            calRequest.setDate(caldate.getTime());

            LegalBasis = Integer.parseInt(dialogo.getLegalBasis()[0].toString());
            Fund = Short.parseShort(dialogo.getFunding()[0].toString());
            Office = selNode.getUID();

            txtBasis.setText(dialogo.getLegalBasis()[1].toString());
            txtFund.setText(dialogo.getFunding()[0] + " - " + dialogo.getFunding()[1]);
            txtResp.setText(selNode.getUID().substring(5) + " " + selNode.getNgalan());
            txtReqBy.setText(selNode.getRequest());
            dialogo.dispose();


            boolean switchOn = dialogo.isChoice();
            calRequest.setEnabled(switchOn);
            calTrnDate.setEnabled(switchOn);
            txtDetail .setEditable(switchOn);
            txtReqBy  .setEditable(switchOn);
            txtDesign .setEditable(switchOn);
            btnAddDoc .setEnabled(switchOn);
            btnAddFPP .setEnabled(switchOn);
            tblDocs   .setEnabled(switchOn);
            tblDetail .setEnabled(switchOn);
            optRegular.setEnabled(switchOn);
            optAdjust .setEnabled(switchOn);

            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblDetail.getModel();
            modelo.setRowCount(0);

            pnlNew.setVisible(switchOn);
            pnlMain.setVisible(!switchOn);
            
            btnEarmark.setEnabled(false);
            txtEarmark.setText("");

        } catch (java.text.ParseException | NumberFormatException mex) {
            javax.swing.JOptionPane.showMessageDialog(this, mex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, mex);
        } finally {
            
        }
    }//GEN-LAST:event_DirectItemActionPerformed

    private void btnAddDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDocActionPerformed
        // TODO add your handling code here:
        DocDialog dialogo = new DocDialog(Office);
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);

        if (!dialogo.isChoice()) {
            dialogo.dispose();
            return;
        }
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblDocs.getModel();
        modelo.setRowCount(0);
        //arDocID.add((Short)dialogo.getSources()[0]);
        Object[] rowData = {
            String.valueOf(dialogo.getDocuments()[0]),
            String.valueOf(dialogo.getDocuments()[1]),
            String.valueOf(dialogo.getDocuments()[2]),
            (Double)dialogo.getDocuments()[3]
        };
        OBLIGE_NO = String.valueOf(dialogo.getDocuments()[1]);
        modelo.insertRow(0/*modelo.getRowCount()*/, rowData);
        txtDetail.setText(dialogo.getDocuments()[4].toString());
        txtReqBy.setText(dialogo.getDocuments()[5].toString());
        txtDesign.setText(dialogo.getDocuments()[6].toString());
        calRequest.setDate((java.util.Date)dialogo.getDocuments()[7]);
        
        btnEarmark.setEnabled(true);
    }//GEN-LAST:event_btnAddDocActionPerformed

    private void EarmarkItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EarmarkItemActionPerformed
        // TODO add your handling code here:
        EarmarkDialog dialogo = new EarmarkDialog(Office);
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);

        if (!dialogo.isChoice()) {
            dialogo.dispose();
            return;
        }

        Object[] earmark = dialogo.getEarmark();
        String  sqlQuery1 = 
                "SELECT " +
                    "ordinances.legal_uid, " +      // 1
                    "ordinances.legal_desc, " +     // 2
                    "earmark_main.fund_acct, " +    // 3
                    "funds.description, " +         // 4
                    "earmark_main.resp_cntr, " +    // 5
                    "offices.description, " +       // 6
                    "earmark_main.particular, " +   // 7
                    "earmark_main.requested, " +    // 8
                    "earmark_main.total_amnt, " +   // 9
                    "earmark_main.transact " +      //10
                "FROM " +
                    "buds.earmark_main JOIN buds.ordinances " +
                    "ON earmark_main.legal_uid = ordinances.legal_uid " +
                    "JOIN buds.fund_control funds " +
                    "ON earmark_main.years = funds.years " +
                    "AND earmark_main.fund_acct::VARCHAR = funds.centre_uid " +
                    "JOIN buds.fund_control offices " +
                    "ON earmark_main.years = offices.years " +
                    "AND earmark_main.resp_cntr = offices.centre_uid " +
                "WHERE " +
                    "(earmark_main.earmrk_id = ?)",
                sqlQuery2 = 
                "SELECT " +
                    "fund_control.description, " +  // 1
                    "accounts.titles, " +           // 2
                    "earmark_sub.acct_code, " +     // 3
                    "earmark_sub.amount, " +        // 4
                    "earmark_sub.ppf_uid, " +       // 5
                    "earmark_sub.classes " +        // 6
                "FROM " +
                    "buds.earmark_sub JOIN buds.fund_control " +
                    "ON earmark_sub.ppf_uid = fund_control.centre_uid " +
                    "AND earmark_sub.years = fund_control.years " +
                    "JOIN acct.accounts " +
                    "ON earmark_sub.acct_code = accounts.coding " +
                "WHERE " +
                    "(earmark_sub.earmrk_id = ?)",
                sqlQuery3 =
                "SELECT " +
                    "COUNT(*) " +
                "FROM " +
                    "buds.earmark_sub " +
                "WHERE " +
                    "(earmrk_id = ?)";
        try (java.sql.Connection jdbc = new budget.DBaseLink();
                java.sql.PreparedStatement psmt1 = jdbc.prepareStatement(sqlQuery1);
                java.sql.PreparedStatement psmt2 = jdbc.prepareStatement(sqlQuery2);
                java.sql.PreparedStatement psmt3 = jdbc.prepareStatement(sqlQuery3)) {
            psmt1.setString(1, earmark[0].toString());
            try (java.sql.ResultSet rst = psmt1.executeQuery()) {
                rst.next();
                
                txtEarmark.setText(earmark[0].toString());
                LegalBasis = rst.getInt(1);
                txtBasis.setText(rst.getString(2));
                Fund = rst.getShort(3);
                txtFund.setText(rst.getString(4));
                Office = rst.getString(5);
                txtResp.setText(rst.getString(6));
                //txtDetail.setText(rst.getString(7));
                //txtReqBy.setText(rst.getString(8));
                //calRequest.setDate(rst.getDate(10));
            }

            int pila_kabook;
            psmt3.setString(1, earmark[0].toString());
            try (java.sql.ResultSet rst = psmt3.executeQuery()) {
                rst.next();
                pila_kabook = rst.getInt(1);
            }
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblDetail.getModel();
            modelo.setRowCount(0);
            psmt2.setString(1, earmark[0].toString());
            try (java.sql.ResultSet rst = psmt2.executeQuery()) {
                int counter = 1; long adder = Math.round(Double.parseDouble(fmtTotalDoc.getValue().toString()) * 100D);
                while (rst.next()) {
                    long rounder = adder / pila_kabook;
                    if (counter == pila_kabook) rounder = adder - (rounder * (pila_kabook - 1));
                    Object[] rowData = {
                        rst.getString(1),
                        rst.getString(2),
                        rst.getString(3),
                        rounder * 0.01D,
                        rst.getString(5)
                    };
                    modelo.addRow(rowData);
                    CLASS_CODE = rst.getString(6);
                    counter++;
                }
            }
            java.util.Calendar caldate = java.util.Calendar.getInstance();
            caldate.setTime(new java.text.SimpleDateFormat("yyyy-MM-dd").parse(System.getProperty("PETSAH")));
            String bulan = new java.text.DecimalFormat("00").format(caldate.get(java.util.Calendar.MONTH) + 1);
            txtTranNo.setText(CLASS_CODE + "-" + caldate.get(java.util.Calendar.YEAR) + "-" + bulan + "-######");
            
            btnAddDoc.setEnabled(true);
            optRegular.setEnabled(true);
            optAdjust.setEnabled(true);
            txtDesign.setEditable(true);
            txtDetail.setEditable(true);
            txtReqBy.setEditable(true);
            txtDesign.setEditable(true);
            calRequest.setEnabled(true);
                    
            pnlNew.setVisible(true);
            pnlMain.setVisible(false);


        } catch (java.sql.SQLException | java.text.ParseException sex) {
            javax.swing.JOptionPane.showMessageDialog(this, sex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, sex);
        } finally {
            
        }
    }//GEN-LAST:event_EarmarkItemActionPerformed

    private void chkMao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMao1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu PopupMenu;
    private javax.swing.JButton btnAddDoc;
    private javax.swing.JButton btnAddFPP;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnClose2;
    private javax.swing.JButton btnClose3;
    private javax.swing.JButton btnDelDoc;
    private javax.swing.JButton btnDelFPP;
    private javax.swing.JButton btnEarmark;
    private javax.swing.JButton btnElisan;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUndo;
    private javax.swing.ButtonGroup buttonGroup;
    private com.toedter.calendar.JDateChooser calRequest;
    private com.toedter.calendar.JDateChooser calTrnDate;
    private javax.swing.JFormattedTextField fmtTotalDet;
    private javax.swing.JFormattedTextField fmtTotalDoc;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JRadioButton optAdjust;
    private javax.swing.JRadioButton optRegular;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlNew;
    private javax.swing.JPanel pnlOpen;
    private javax.swing.JTable tblDetail;
    private javax.swing.JTable tblDocs;
    private javax.swing.JTextField txtApprvBy;
    private javax.swing.JTextField txtBasis;
    private javax.swing.JTextField txtDesign;
    private javax.swing.JTextArea txtDetail;
    private javax.swing.JTextField txtEarmark;
    private javax.swing.JTextField txtFund;
    private javax.swing.JTextField txtPrepBy;
    private javax.swing.JTextField txtReqBy;
    private javax.swing.JTextField txtResp;
    private javax.swing.JTextField txtRevwBy;
    private javax.swing.JTextField txtTranNo;
    // End of variables declaration//GEN-END:variables

    private String CLASS_CODE = "",
                   OBLIGE_NO;
    
    private Integer LegalBasis;
    private Short   Fund;
    private String  Office;

//    private final javax.swing.table.DefaultTableModel DetTblModel = new javax.swing.table.DefaultTableModel(
//            new Object[][]{},
//            new String[]{
//                "FPP", "Account Title", "Acct Code", "Amount", "ppf_id"
//                /* 0 ,  1,               2,           3,        4,   */
//            }
//    ) {
//        Class[] types = new Class[]{
//            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
//        };
//        boolean[] canEdit = new boolean[]{
//            false, false, false, false, false
//        };
//
//        @Override
//        public Class getColumnClass(int columnIndex) {
//            return types[columnIndex];
//        }
//
//        @Override
//        public boolean isCellEditable(int rowIndex, int columnIndex) {
//            return canEdit[columnIndex];
//        }
//
//        @Override
//        public void setValueAt(Object aValue, int row, int col) {
//            switch (col) {
//                case 3:
//                    double amount = (Double)aValue,
//                           allots = (Double) getValueAt(row, 4),
//                           oldval = (Double) getValueAt(row, col);
//                    if (amount > allots) {
//                        classes.MsgBox.showWarning(PrepareForm.this, "Amount exceeded from balance.", title);
//                        aValue = oldval;
//                    }
//            }
//            super.setValueAt(aValue, row, col);
//        }
//    };
}
