package budget;

/**
 *
 * @author felix
 */
public class MainFrame extends javax.swing.JFrame {

    private setting.ResOrdForm                  frmResOrd;
    private setting.FunctionForm                frmFunction;
    private setting.AccountForm                 frmAccount;

    private earmark.prep.PrepareForm            frmEarmPrep;
    private earmark.cncl.VoidForm               frmEarmCncl;

    private oblige.prep.PrepareForm             frmObligPrep;
    
    private transaction.appropriation.FrmPrepAppropriation      appropriation;
    private transaction.appropriation.FrmAppropApproval         approp_approv;
    private transaction.appropriation.FrmAppropCancellation     approp_cancel;
    private transaction.allotment.FrmPrepAllotment              allotment;
    private transaction.allotment.FrmApprovalAllotment          allot_approv;


    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setExtendedState(getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        //mdiDesktopPane.setBackgroundImage(getClass().getResource("/imahen/background.jpg"), true);
        mdiDesktopPane.setBackgroundImage(getClass().getResource("/images/sc.png"), true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        mdiDesktopPane = new mdiMenu.MDIDesktopPane();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        txtDateTime = new javax.swing.JTextField();
        javax.swing.JMenuBar MenuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu SettingMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem FunctionItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem ResOrdItem = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator1 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem AcctChartItem = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator3 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem DocsItem = new javax.swing.JMenuItem();
        javax.swing.JMenu Budget = new javax.swing.JMenu();
        javax.swing.JMenu AppropMenu = new javax.swing.JMenu();
        javax.swing.JMenu CurrAppMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem ApprPrepareItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem ApprApproveItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem ApprCancelItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem CancelItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenu AllocateMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem AllotPrepareItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem AllotApproveItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem AllotCancelItem = new javax.swing.JMenuItem();
        javax.swing.JMenu RealignMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem AlignPrepareItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem AlignApproveItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem AlignCancelItem = new javax.swing.JMenuItem();
        javax.swing.JMenu ReverseMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem RevPrepareItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem RevApproveItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem RevCancelItem = new javax.swing.JMenuItem();
        javax.swing.JMenu SupplyMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem SuppPrepareItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem SuppApproveItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem SuppCancelItem = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator2 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenu EarmarkMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem EarPrepareItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem EarCancelItem = new javax.swing.JMenuItem();
        javax.swing.JMenu ObligateMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem ObligePrepareItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem ObligeApproveItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem ObligeCancelItem = new javax.swing.JMenuItem();
        javax.swing.JMenu SystemMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem QuitItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Budget monitoring");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imahen/budget.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setViewportView(mdiDesktopPane);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Current User:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        txtUser.setEditable(false);
        txtUser.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 2, 250, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Date & Time:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 5, -1, -1));

        txtDateTime.setEditable(false);
        txtDateTime.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(txtDateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 2, 300, -1));

        SettingMenu.setText("Settings");
        SettingMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        FunctionItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        FunctionItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/title.png"))); // NOI18N
        FunctionItem.setText("Funds/Property/Project");
        FunctionItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FunctionItemActionPerformed(evt);
            }
        });
        SettingMenu.add(FunctionItem);

        ResOrdItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ResOrdItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/office_setup.png"))); // NOI18N
        ResOrdItem.setText("Appropriation Ordinances");
        ResOrdItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResOrdItemActionPerformed(evt);
            }
        });
        SettingMenu.add(ResOrdItem);

        jSeparator1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        SettingMenu.add(jSeparator1);

        AcctChartItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        AcctChartItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/account.png"))); // NOI18N
        AcctChartItem.setText("Chart of Accounts");
        AcctChartItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcctChartItemActionPerformed(evt);
            }
        });
        SettingMenu.add(AcctChartItem);
        SettingMenu.add(jSeparator3);

        DocsItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        DocsItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/document.png"))); // NOI18N
        DocsItem.setText("Documents");
        DocsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocsItemActionPerformed(evt);
            }
        });
        SettingMenu.add(DocsItem);

        MenuBar.add(SettingMenu);

        Budget.setText("Transaction");
        Budget.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        AppropMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/approp.png"))); // NOI18N
        AppropMenu.setText("Appropriation");
        AppropMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        CurrAppMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/current.png"))); // NOI18N
        CurrAppMenu.setText("Current");
        CurrAppMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        ApprPrepareItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ApprPrepareItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/prepare.png"))); // NOI18N
        ApprPrepareItem.setText("Preparation");
        ApprPrepareItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApprPrepareItemActionPerformed(evt);
            }
        });
        CurrAppMenu.add(ApprPrepareItem);

        ApprApproveItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ApprApproveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/approval.png"))); // NOI18N
        ApprApproveItem.setText("Approval");
        ApprApproveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApprApproveItemActionPerformed(evt);
            }
        });
        CurrAppMenu.add(ApprApproveItem);

        ApprCancelItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ApprCancelItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/cancel.png"))); // NOI18N
        ApprCancelItem.setText("Cancellation");
        ApprCancelItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApprCancelItemActionPerformed(evt);
            }
        });
        CurrAppMenu.add(ApprCancelItem);

        AppropMenu.add(CurrAppMenu);

        CancelItem1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        CancelItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/continue.png"))); // NOI18N
        CancelItem1.setText("Continuing");
        AppropMenu.add(CancelItem1);

        Budget.add(AppropMenu);

        AllocateMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/allocate.png"))); // NOI18N
        AllocateMenu.setText("Advice of Allotment");
        AllocateMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        AllotPrepareItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        AllotPrepareItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/prepare.png"))); // NOI18N
        AllotPrepareItem.setText("Preparation");
        AllotPrepareItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllotPrepareItemActionPerformed(evt);
            }
        });
        AllocateMenu.add(AllotPrepareItem);

        AllotApproveItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        AllotApproveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/approval.png"))); // NOI18N
        AllotApproveItem.setText("Approval");
        AllotApproveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllotApproveItemActionPerformed(evt);
            }
        });
        AllocateMenu.add(AllotApproveItem);

        AllotCancelItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        AllotCancelItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/cancel.png"))); // NOI18N
        AllotCancelItem.setText("Cancellation");
        AllocateMenu.add(AllotCancelItem);

        Budget.add(AllocateMenu);

        RealignMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/realign.png"))); // NOI18N
        RealignMenu.setText("Realignment");
        RealignMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        AlignPrepareItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        AlignPrepareItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/prepare.png"))); // NOI18N
        AlignPrepareItem.setText("Preparation");
        RealignMenu.add(AlignPrepareItem);

        AlignApproveItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        AlignApproveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/approval.png"))); // NOI18N
        AlignApproveItem.setText("Approval");
        RealignMenu.add(AlignApproveItem);

        AlignCancelItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        AlignCancelItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/cancel.png"))); // NOI18N
        AlignCancelItem.setText("Cancellation");
        RealignMenu.add(AlignCancelItem);

        Budget.add(RealignMenu);

        ReverseMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/reverse.png"))); // NOI18N
        ReverseMenu.setText("Reversion");
        ReverseMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        RevPrepareItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RevPrepareItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/prepare.png"))); // NOI18N
        RevPrepareItem.setText("Preparation");
        ReverseMenu.add(RevPrepareItem);

        RevApproveItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RevApproveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/approval.png"))); // NOI18N
        RevApproveItem.setText("Approval");
        ReverseMenu.add(RevApproveItem);

        RevCancelItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RevCancelItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/cancel.png"))); // NOI18N
        RevCancelItem.setText("Cancellation");
        ReverseMenu.add(RevCancelItem);

        Budget.add(ReverseMenu);

        SupplyMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/supplemental.png"))); // NOI18N
        SupplyMenu.setText("Supplemental");
        SupplyMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        SuppPrepareItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        SuppPrepareItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/prepare.png"))); // NOI18N
        SuppPrepareItem.setText("Preparation");
        SupplyMenu.add(SuppPrepareItem);

        SuppApproveItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        SuppApproveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/approval.png"))); // NOI18N
        SuppApproveItem.setText("Approval");
        SupplyMenu.add(SuppApproveItem);

        SuppCancelItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        SuppCancelItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/cancel.png"))); // NOI18N
        SuppCancelItem.setText("Cancellation");
        SupplyMenu.add(SuppCancelItem);

        Budget.add(SupplyMenu);
        Budget.add(jSeparator2);

        EarmarkMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/earmark.png"))); // NOI18N
        EarmarkMenu.setText("Earmark");
        EarmarkMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        EarPrepareItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        EarPrepareItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/prepare.png"))); // NOI18N
        EarPrepareItem.setText("Preparation");
        EarPrepareItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EarPrepareItemActionPerformed(evt);
            }
        });
        EarmarkMenu.add(EarPrepareItem);

        EarCancelItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        EarCancelItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/cancel.png"))); // NOI18N
        EarCancelItem.setText("Cancellation");
        EarCancelItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EarCancelItemActionPerformed(evt);
            }
        });
        EarmarkMenu.add(EarCancelItem);

        Budget.add(EarmarkMenu);

        ObligateMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/obligation.png"))); // NOI18N
        ObligateMenu.setText("Obligation");
        ObligateMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        ObligePrepareItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ObligePrepareItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/prepare.png"))); // NOI18N
        ObligePrepareItem.setText("Preparation");
        ObligePrepareItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObligePrepareItemActionPerformed(evt);
            }
        });
        ObligateMenu.add(ObligePrepareItem);

        ObligeApproveItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ObligeApproveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/approval.png"))); // NOI18N
        ObligeApproveItem.setText("Approval");
        ObligeApproveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObligeApproveItemActionPerformed(evt);
            }
        });
        ObligateMenu.add(ObligeApproveItem);

        ObligeCancelItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ObligeCancelItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/cancel.png"))); // NOI18N
        ObligeCancelItem.setText("Cancellation");
        ObligeCancelItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObligeCancelItemActionPerformed(evt);
            }
        });
        ObligateMenu.add(ObligeCancelItem);

        Budget.add(ObligateMenu);

        MenuBar.add(Budget);

        SystemMenu.setText("System");
        SystemMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        QuitItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        QuitItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/quit.png"))); // NOI18N
        QuitItem.setText("Quit System");
        QuitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitItemActionPerformed(evt);
            }
        });
        SystemMenu.add(QuitItem);

        MenuBar.add(SystemMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(0, 0, 1009, 737);
    }// </editor-fold>//GEN-END:initComponents

    private void QuitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitItemActionPerformed
        // TODO add your handling code here:
        dispatchEvent(new java.awt.event.WindowEvent(this, java.awt.event.WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_QuitItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        boolean test = false;
        try (java.sql.Connection jdbc = new DBaseLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement("UPDATE buds.userlogon SET log_out = NOW() WHERE (userid = ?)")) {
            psmt.setString(1, System.getProperty("USERID"));
            psmt.executeUpdate();
            test = true;

        } catch (Exception ex) {
            classes.MsgBox.showError(MainFrame.this, ex.getMessage(), getTitle());
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {
            if (test) System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (System.getProperty("KARONG") != null) {
            mPetsa.setTimeInMillis(Long.valueOf(System.getProperty("KARONG")));
            if (!orasan.isRunning()) orasan.start();
        }
    }//GEN-LAST:event_formWindowActivated

    private void ResOrdItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResOrdItemActionPerformed
        // TODO add your handling code here:
        try {
            frmResOrd = (setting.ResOrdForm) mdiDesktopPane.PackUpFrame(frmResOrd, setting.ResOrdForm.class.getName());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ResOrdItemActionPerformed

    private void FunctionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FunctionItemActionPerformed
        // TODO add your handling code here:
        try {
            frmFunction = (setting.FunctionForm) mdiDesktopPane.PackUpFrame(frmFunction, setting.FunctionForm.class.getName());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FunctionItemActionPerformed

    private void AcctChartItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcctChartItemActionPerformed
        // TODO add your handling code here:
        try {
            frmAccount = (setting.AccountForm) mdiDesktopPane.PackUpFrame(frmAccount, setting.AccountForm.class.getName());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AcctChartItemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void EarPrepareItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EarPrepareItemActionPerformed
        // TODO add your handling code here:
        try {
            frmEarmPrep = (earmark.prep.PrepareForm) mdiDesktopPane.PackUpFrame(frmEarmPrep, earmark.prep.PrepareForm.class.getName());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EarPrepareItemActionPerformed

    private void EarCancelItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EarCancelItemActionPerformed
        // TODO add your handling code here:
        try {
            frmEarmCncl = (earmark.cncl.VoidForm) mdiDesktopPane.PackUpFrame(frmEarmCncl, earmark.cncl.VoidForm.class.getName());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EarCancelItemActionPerformed

    private void ObligePrepareItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObligePrepareItemActionPerformed
        // TODO add your handling code here:
        try {
            frmObligPrep = (oblige.prep.PrepareForm) mdiDesktopPane.PackUpFrame(frmObligPrep, oblige.prep.PrepareForm.class.getName());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ObligePrepareItemActionPerformed

    private void ObligeApproveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObligeApproveItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObligeApproveItemActionPerformed

    private void ObligeCancelItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObligeCancelItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObligeCancelItemActionPerformed

    private void DocsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocsItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocsItemActionPerformed

    private void ApprPrepareItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApprPrepareItemActionPerformed
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try {
            appropriation = (transaction.appropriation.FrmPrepAppropriation) mdiDesktopPane.PackUpFrame(appropriation, transaction.appropriation.FrmPrepAppropriation.class.getName());
            appropriation.setMaximum(true);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_ApprPrepareItemActionPerformed

    private void ApprApproveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApprApproveItemActionPerformed
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try {
            approp_approv = (transaction.appropriation.FrmAppropApproval) mdiDesktopPane.PackUpFrame(approp_approv, transaction.appropriation.FrmAppropApproval.class.getName());
            approp_approv.setMaximum(true);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_ApprApproveItemActionPerformed

    private void AllotPrepareItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllotPrepareItemActionPerformed
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try {
            allotment= (transaction.allotment.FrmPrepAllotment) mdiDesktopPane.PackUpFrame(allotment, transaction.allotment.FrmPrepAllotment.class.getName());
            allotment.setMaximum(true);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_AllotPrepareItemActionPerformed

    private void AllotApproveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllotApproveItemActionPerformed
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try {
            allot_approv = (transaction.allotment.FrmApprovalAllotment) mdiDesktopPane.PackUpFrame(allot_approv, transaction.allotment.FrmApprovalAllotment.class.getName());
            allot_approv.setMaximum(true);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_AllotApproveItemActionPerformed

    private void ApprCancelItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApprCancelItemActionPerformed
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try {
            approp_cancel= (transaction.appropriation.FrmAppropCancellation) mdiDesktopPane.PackUpFrame(approp_cancel, transaction.appropriation.FrmAppropCancellation.class.getName());
            approp_cancel.setMaximum(false);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_ApprCancelItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mdiMenu.MDIDesktopPane mdiDesktopPane;
    private javax.swing.JTextField txtDateTime;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private java.util.Calendar mPetsa = java.util.Calendar.getInstance();
    
    private final javax.swing.Timer  orasan  = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            //if (jae.getActionCommand().equals("Test")) return;
            /*
            Recabo
            Almeda
            */
            mPetsa.add(java.util.Calendar.SECOND, 1);
            txtDateTime.setText(new java.text.SimpleDateFormat("MMMM dd, yyyy hh:mm:ss a").format(mPetsa.getTime()));

            txtUser.setText(System.getProperty("USERNAME"));
        }
    });
}
