package setting;

/**
 *
 * @author felix
 */
public class OfficeDialog extends javax.swing.JDialog {

    private final java.util.List<Object[]> aRowData = new java.util.ArrayList();
    
    public OfficeDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableModel = new javax.swing.table.DefaultTableModel();
        btnInsert = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOffice = new javax.swing.JTable();

        setTitle("Office Dialog");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnInsert.setText("INSERT");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tblOffice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "X", "ID #", "ACRONYM", "OFFICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOffice.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblOffice.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblOffice);
        if (tblOffice.getColumnModel().getColumnCount() > 0) {
            tblOffice.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblOffice.getColumnModel().getColumn(1).setPreferredWidth(70);
            tblOffice.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblOffice.getColumnModel().getColumn(3).setPreferredWidth(340);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInsert))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnInsert});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnInsert))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(btnInsert);

        setSize(new java.awt.Dimension(609, 522));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        for (short abc = 0; abc < tableModel.getRowCount(); abc++) {
            if (Boolean.valueOf(tableModel.getValueAt(abc, 0).toString()))
                aRowData.add(new Object[] {
                    tableModel.getValueAt(abc, 1),
                    tableModel.getValueAt(abc, 3),
                    null
            });
        }
        setVisible(false);
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
        tableModel.setRowCount(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String sqlCommand = 
                "SELECT " +
                    "resp_code, " +
                    "acronym, " +
                    "description " +
                "FROM " +
                    "public.resp_center " +
                "WHERE " +
                    "(tagoon = FALSE) " +
                "ORDER BY " +
                    "resp_code";
        try (budget.DBaseLink jdbc = new budget.DBaseLink();
                java.sql.Statement stmt = jdbc.createStatement(java.sql.ResultSet.TYPE_SCROLL_INSENSITIVE, java.sql.ResultSet.CONCUR_READ_ONLY);
                java.sql.ResultSet rst = stmt.executeQuery(sqlCommand)) {
            tableModel = (javax.swing.table.DefaultTableModel)tblOffice.getModel();
            tableModel.setRowCount(0);
            while(rst.next()) {
                Object[] rowData = {
                    false,
                    rst.getString(1),
                    rst.getString(2),
                    rst.getString(3)
                };
                tableModel.addRow(rowData);
            }


        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(OfficeDialog.this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(OfficeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {
            
        }
    }//GEN-LAST:event_formWindowOpened



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnInsert;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.table.DefaultTableModel tableModel;
    private javax.swing.JTable tblOffice;
    // End of variables declaration//GEN-END:variables

    public java.util.List<Object[]> getData() {return aRowData;}
}
