/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package transaction.appropriation;

import java.lang.reflect.Field;
import javax.swing.JButton;


/**
 *
 * @author theamateurish
 */
public class DlgBugdetAppropriation extends javax.swing.JDialog {

    private String appPath = System.getProperties().getProperty("user.dir");
    private boolean editMode,readOnly;
    private Integer legalID,fundID,year;
    private String legalDesc,fundDesc,controlID;
    private final boolean NUMERIC = true;  
    
    /**
     * Creates new form ModifyPreparation
     */
    public DlgBugdetAppropriation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        load();
    }
    
    private void load(){
        setEditMode(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        connect.DBConnection dbc = null;
        java.sql.PreparedStatement preparedStatement = null;
        String selectSQL="SELECT t1.fund_id,t1.legal_base,t1.control_id,t1.status,t1.date_prepared,"
                + "t2.description,t3.legal_desc,t3.legal_year FROM buds.appropriation_status t1 "
                + "INNER JOIN temp.prep_respcenter t2 "
                + "ON t1.legal_base=t2.legal_base AND t1.fund_id=t2.funds_id "
                + "INNER JOIN buds.ordinances t3 ON t1.legal_base=t3.legal_uid "
                + "WHERE resp_id=0 "
                + "AND resp_sub=0 "
                + "AND programs=0 "
                + "AND classes=0 "
                + "AND t3.legal_year=? "
                + "ORDER BY t1.control_id";               

        try {
                dbc = new connect.DBConnection();
                preparedStatement = dbc.prepareStatement(selectSQL);
                preparedStatement.setInt(1, Integer.valueOf(System.getProperty("systemYear")));
                java.sql.ResultSet rs = preparedStatement.executeQuery();
                classes.utils.clearTable(tblRecords);
                int R=0;
                while(rs.next()) {                                       
                    if (R >=tblRecords.getRowCount()){
                                    ((javax.swing.table.DefaultTableModel)tblRecords.getModel()).addRow(new Object[] {null, null, null, null, null});
                    } 
                    tblRecords.setValueAt(rs.getString("control_id"), R, 0);
                    tblRecords.setValueAt(rs.getInt("legal_year"), R, 1);
                    tblRecords.setValueAt(rs.getString("legal_desc"), R, 2);  
                    tblRecords.setValueAt(rs.getString("description"), R, 3);
                    tblRecords.setValueAt(rs.getString("status"), R, 4);
                    tblRecords.setValueAt(rs.getInt("legal_base"), R, 5);  
                    tblRecords.setValueAt(rs.getInt("fund_id"), R, 6);
                    R++;
                }

                preparedStatement.close();
                rs.close();                        

        } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Select Records", javax.swing.JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger("DlgBudgetAppropriation").log(java.util.logging.Level.SEVERE, null, e);
        } finally {
                if (dbc != null) try {
                    dbc.close();
                } catch (java.sql.SQLException ex) {
                    javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "CLOSING CONNECTION", javax.swing.JOptionPane.ERROR_MESSAGE);
                    java.util.logging.Logger.getLogger("DlgBudgetAppropriation").log(java.util.logging.Level.SEVERE, null, ex);
                }
        }
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecords = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnPreview = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Legal Base / Fund");
        setResizable(false);

        tblRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CONTROL#", "YEAR", "LEGAL BASIS", "FUND ACCOUNT", "STATUS", "LEGAL", "CTRLUID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRecords.getTableHeader().setReorderingAllowed(false);
        tblRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRecordsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRecords);
        tblRecords.getColumnModel().getColumn(0).setMinWidth(100);
        tblRecords.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblRecords.getColumnModel().getColumn(0).setMaxWidth(100);
        tblRecords.getColumnModel().getColumn(1).setMinWidth(50);
        tblRecords.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblRecords.getColumnModel().getColumn(1).setMaxWidth(50);
        tblRecords.getColumnModel().getColumn(4).setMinWidth(100);
        tblRecords.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblRecords.getColumnModel().getColumn(4).setMaxWidth(100);
        tblRecords.getColumnModel().getColumn(5).setMinWidth(0);
        tblRecords.getColumnModel().getColumn(5).setPreferredWidth(0);
        tblRecords.getColumnModel().getColumn(5).setMaxWidth(0);
        tblRecords.getColumnModel().getColumn(6).setMinWidth(0);
        tblRecords.getColumnModel().getColumn(6).setPreferredWidth(0);
        tblRecords.getColumnModel().getColumn(6).setMaxWidth(0);

        btnEdit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnPreview.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnPreview.setText("Print Preview");
        btnPreview.setEnabled(false);
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPreview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnPreview)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        setLegalID(Integer.valueOf(tblRecords.getValueAt(tblRecords.getSelectedRow(), 5).toString()));  
        setFundID(Integer.valueOf(tblRecords.getValueAt(tblRecords.getSelectedRow(), 6).toString()));
        setFundDesc(tblRecords.getValueAt(tblRecords.getSelectedRow(), 3).toString());
        setLegalDesc(tblRecords.getValueAt(tblRecords.getSelectedRow(), 2).toString());
        setControlID(tblRecords.getValueAt(tblRecords.getSelectedRow(), 0).toString());
        setEditMode(true);
        setReadOnly(false);
        dispose();
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRecordsMouseClicked
        setLegalID(Integer.valueOf(tblRecords.getValueAt(tblRecords.getSelectedRow(), 5).toString()));  
        setFundID(Integer.valueOf(tblRecords.getValueAt(tblRecords.getSelectedRow(), 6).toString()));
        setFundDesc(tblRecords.getValueAt(tblRecords.getSelectedRow(), 3).toString());
        setLegalDesc(tblRecords.getValueAt(tblRecords.getSelectedRow(), 2).toString());
        setControlID(tblRecords.getValueAt(tblRecords.getSelectedRow(), 0).toString());
        if(tblRecords.getValueAt(tblRecords.getSelectedRow(), 4).equals("Approved")|tblRecords.getValueAt(tblRecords.getSelectedRow(), 4).equals("Cancelled")){        
            btnEdit.setEnabled(false);
        }else{
            btnEdit.setEnabled(true);
        }
        btnPreview.setEnabled(tblRecords.getSelectedRow()>=0 & !tblRecords.getValueAt(tblRecords.getSelectedRow(), 4).equals("Cancelled"));
    }//GEN-LAST:event_tblRecordsMouseClicked

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        setEditMode(false);
        setReadOnly(true);
        dispose();
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        java.io.InputStream reportSource = null;
        String reportDest = "";
        try {
            reportSource = getClass().getResource("/budget/stmtApprop.jasper").openStream();
            reportDest = appPath + "/results/stmtApprop.html";

            java.io.File file = new java.io.File(appPath + "/results");
            if (!file.isDirectory()) file.mkdir();

            java.util.Map<String, Object> params = new java.util.HashMap<String, Object>();

            org.apache.log4j.Logger logger = org.apache.log4j.Logger.getRootLogger();
            logger.setLevel((org.apache.log4j.Level)org.apache.log4j.Level.WARN);

            // REPORT PARAMETERS
            java.awt.Image logo=new javax.swing.ImageIcon(getClass().getResource("/images/SC.jpg")).getImage();
            params.put("LogoSC",logo);
            params.put("legal",Integer.valueOf(tblRecords.getValueAt(tblRecords.getSelectedRow(), 5).toString()));
            params.put("fund",Integer.valueOf(tblRecords.getValueAt(tblRecords.getSelectedRow(), 6).toString()));
            params.put("fund_desc",tblRecords.getValueAt(tblRecords.getSelectedRow(),3).toString());

            net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportSource, params, new connect.DBConnection().getLink());
            //            net.sf.jasperreports.engine.JasperPrintManager.printReport(jasperPrint, true);
            net.sf.jasperreports.view.JasperViewer jv=new net.sf.jasperreports.view.JasperViewer(jasperPrint,false);
            jv.setTitle(tblRecords.getValueAt(tblRecords.getSelectedRow(), 0).toString());
            jv.setVisible(true);
            new connect.DBConnection().close();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger("DlgBudgetAppropriation").log(java.util.logging.Level.SEVERE, null, ex);
        }
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
       dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    public boolean isEditMode() {
        return editMode;
    }

    public void setEditMode(boolean editMode) {
        this.editMode = editMode;
    }   

    public boolean isReadOnly() {
        return readOnly;
    }

    public void setReadOnly(boolean readOnly) {
        this.readOnly = readOnly;
    }   
    

    public Integer getLegalID() {
        return legalID;
    }

    public void setLegalID(Integer legalID) {
        this.legalID = legalID;
    }

    public Integer getFundID() {
        return fundID;
    }

    public void setFundID(Integer fundID) {
        this.fundID = fundID;
    }

    public String getControlID() {
        return controlID;
    }

    public void setControlID(String controlID) {
        this.controlID = controlID;
    }    

    public String getLegalDesc() {
        return legalDesc;
    }

    public void setLegalDesc(String legalDesc) {
        this.legalDesc = legalDesc;
    }

    public String getFundDesc() {
        return fundDesc;
    }

    public void setFundDesc(String fundDesc) {
        this.fundDesc = fundDesc;
    }
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnPreview;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRecords;
    // End of variables declaration//GEN-END:variables
}
