/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package transaction.appropriation;

/**
 *
 * @author theamateurish
 */
public class FrmAppropCancellation extends javax.swing.JInternalFrame {
private final boolean NUMERIC = true;  
private String appPath = System.getProperties().getProperty("user.dir");
    /**
     * Creates new form FrmAppropCancellation
     */
    public FrmAppropCancellation() {
        initComponents();
        loadAppropriation();
    }

    private void loadAppropriation(){
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        connect.DBConnection dbc = null;
        java.sql.PreparedStatement preparedStatement = null;
        String selectSQL="SELECT t1.fund_id,t1.legal_base,t1.control_id,t1.status,t1.date_prepared,"
                + "t2.description,t3.legal_desc,t3.legal_year FROM buds.appropriation_status t1 "
                + "INNER JOIN temp.prep_respcenter t2 "
                + "ON t1.legal_base=t2.legal_base AND t1.fund_id=t2.funds_id "
                + "INNER JOIN buds.ordinances t3 ON t1.legal_base=t3.legal_uid "
                + "WHERE resp_id=0 "
                + "AND resp_sub=0 "
                + "AND programs=0 "
                + "AND classes=0 "
                + "AND t3.legal_year=? "
                + "AND t1.status='For Review' "
                + "ORDER BY t1.fund_id";               

        try {
                dbc = new connect.DBConnection();
                preparedStatement = dbc.prepareStatement(selectSQL);
                preparedStatement.setInt(1, Integer.valueOf(System.getProperty("systemYear")));
                java.sql.ResultSet rs = preparedStatement.executeQuery();
                classes.utils.clearTable(tblRecords);
                int R=0;
                while(rs.next()) {                                       
                    if (R >=tblRecords.getRowCount()){
                                    ((javax.swing.table.DefaultTableModel)tblRecords.getModel()).addRow(new Object[] {null, null, null, null, null});
                    } 
                    tblRecords.setValueAt(rs.getString("control_id"), R, 0);
                    tblRecords.setValueAt(rs.getInt("legal_year"), R, 1);
                    tblRecords.setValueAt(rs.getString("legal_desc"), R, 2);  
                    tblRecords.setValueAt(rs.getString("description"), R, 3);
                    tblRecords.setValueAt(rs.getString("status"), R, 4);
                    tblRecords.setValueAt(rs.getInt("legal_base"), R, 5);  
                    tblRecords.setValueAt(rs.getInt("fund_id"), R, 6);
                    R++;
                }

                preparedStatement.close();
                rs.close();                        

        } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Select Records", javax.swing.JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger("FrmAppropCancellation").log(java.util.logging.Level.SEVERE, null, e);
        } finally {
                if (dbc != null) try {
                    dbc.close();
                } catch (java.sql.SQLException ex) {
                    javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "CLOSING CONNECTION", javax.swing.JOptionPane.ERROR_MESSAGE);
                    java.util.logging.Logger.getLogger("FrmAppropCancellation").log(java.util.logging.Level.SEVERE, null, ex);
                }
        }
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecords = new javax.swing.JTable();
        btnPreview = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setClosable(true);

        tblRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CONTROL#", "YEAR", "LEGAL BASIS", "FUND ACCOUNT", "STATUS", "LEGAL", "CTRLUID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRecords.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblRecords);
        tblRecords.getColumnModel().getColumn(0).setMinWidth(100);
        tblRecords.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblRecords.getColumnModel().getColumn(0).setMaxWidth(100);
        tblRecords.getColumnModel().getColumn(1).setMinWidth(50);
        tblRecords.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblRecords.getColumnModel().getColumn(1).setMaxWidth(50);
        tblRecords.getColumnModel().getColumn(5).setMinWidth(0);
        tblRecords.getColumnModel().getColumn(5).setPreferredWidth(0);
        tblRecords.getColumnModel().getColumn(5).setMaxWidth(0);
        tblRecords.getColumnModel().getColumn(6).setMinWidth(0);
        tblRecords.getColumnModel().getColumn(6).setPreferredWidth(0);
        tblRecords.getColumnModel().getColumn(6).setMaxWidth(0);

        btnPreview.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnPreview.setText("Print Preview");
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnCancel.setText("Cancel Appropriation");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addComponent(btnPreview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnPreview))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
       
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        java.io.InputStream reportSource = null;
        String reportDest = "";
        try {
            reportSource = getClass().getResource("/budget/stmtApprop.jasper").openStream();
            reportDest = appPath + "/results/stmtApprop.html";

            java.io.File file = new java.io.File(appPath + "/results");
            if (!file.isDirectory()) file.mkdir();

            java.util.Map<String, Object> params = new java.util.HashMap<String, Object>();

            org.apache.log4j.Logger logger = org.apache.log4j.Logger.getRootLogger();
            logger.setLevel((org.apache.log4j.Level)org.apache.log4j.Level.WARN);

            // REPORT PARAMETERS
            java.awt.Image logo=new javax.swing.ImageIcon(getClass().getResource("/images/SC.jpg")).getImage();
            params.put("LogoSC",logo);
            params.put("legal",Integer.valueOf(tblRecords.getValueAt(tblRecords.getSelectedRow(), 5).toString()));
            params.put("fund",Integer.valueOf(tblRecords.getValueAt(tblRecords.getSelectedRow(), 6).toString()));
            params.put("fund_desc",tblRecords.getValueAt(tblRecords.getSelectedRow(),3).toString());

            net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportSource, params, new connect.DBConnection().getLink());
            //            net.sf.jasperreports.engine.JasperPrintManager.printReport(jasperPrint, true);
            net.sf.jasperreports.view.JasperViewer jv=new net.sf.jasperreports.view.JasperViewer(jasperPrint,false);
            jv.setTitle(tblRecords.getValueAt(tblRecords.getSelectedRow(), 0).toString());
            jv.setVisible(true);
            new connect.DBConnection().close();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger("FrmAppropCancellation").log(java.util.logging.Level.SEVERE, null, ex);
        }
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        connect.DBConnection dbc = null;
        int success=0;
        try {
            dbc = new connect.DBConnection();
            dbc.setAutoCommit(false);
            dbase.SQLExecute deleteApplication = new dbase.SQLExecute("buds.appropriation_status");
            deleteApplication.FieldName("fund_id",  NUMERIC, enums.Take.InsertUpdate, true,Integer.valueOf(tblRecords.getValueAt(tblRecords.getSelectedRow(), 6).toString()));
            deleteApplication.FieldName("legal_base",  NUMERIC, enums.Take.InsertUpdate,true,Integer.valueOf(tblRecords.getValueAt(tblRecords.getSelectedRow(), 5).toString()));
            deleteApplication.FieldName("date_prepared",   !NUMERIC, enums.Take.InsertUpdate, new connect.SystemOptions().ServerDate());
            deleteApplication.FieldName("status",  !NUMERIC, enums.Take.InsertUpdate,"Cancelled");
            success=dbc.executeUpdate(deleteApplication.Perform(enums.Fire.doUpdate));

            if(success>0){
                int resp=classes.MsgBox.showConfirm(this,"Are you sure you want to cancel this transaction?\nOnce you continue this, you cannot undo the entries you've made.", getTitle());
                if(resp==javax.swing.JOptionPane.YES_OPTION){
                    dbc.commit();
                    dbc.close();
                    classes.MsgBox.showInfo(this, "Record cancelled successfully.", getTitle());
                    loadAppropriation();
                }
            }

        } catch (Exception ex) {
            if (dbc != null) try {
                dbc.rollback();
            } catch (Exception rlbk) {
                java.util.logging.Logger.getLogger("FrmAppropCancellation").log(java.util.logging.Level.SEVERE, null, rlbk);
            }
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
            java.util.logging.Logger.getLogger("FrmAppropCancellation").log(java.util.logging.Level.SEVERE, null, ex);

        } finally {
            if (dbc != null) try {
                dbc.close();
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger("FrmAppropCancellation").log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPreview;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRecords;
    // End of variables declaration//GEN-END:variables
}
