package earmark.cncl;

/**
 *
 * @author felix
 */
public class VoidForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form EarmarkPrepareForm
     */
    public VoidForm() {
        initComponents();
        
//        String trgSearch = "Search";
//        javax.swing.InputMap inputMap = getRootPane().getInputMap(javax.swing.JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
//        inputMap.put(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0), trgSearch);
//        javax.swing.ActionMap actionMap = getRootPane().getActionMap();
//        actionMap.put(trgSearch, new javax.swing.AbstractAction() {
//            @Override
//            public void actionPerformed(java.awt.event.ActionEvent ae) {
//                //cancelButtonActionPerformed(ae);
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEarmark = new javax.swing.JTable();
        javax.swing.JButton btnSearch = new javax.swing.JButton();
        lblSelected = new javax.swing.JLabel();
        chkAll = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        javax.swing.JButton btnCancel = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setClosable(true);
        setTitle("Earmark - Cancellation");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Search Particular");

        tblEarmark.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "*", "Tran. No.", "Date", "Amount", "Particular"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEarmark.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblEarmark.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblEarmark);
        if (tblEarmark.getColumnModel().getColumnCount() > 0) {
            tblEarmark.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblEarmark.getColumnModel().getColumn(1).setPreferredWidth(130);
            tblEarmark.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblEarmark.getColumnModel().getColumn(2).setCellRenderer(new tables.LabelColumnRender(tables.LabelColumnRender.CENTER));
            tblEarmark.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblEarmark.getColumnModel().getColumn(3).setCellRenderer(new tables.DecimalFormatColumnRender(tables.DecimalFormatColumnRender.COMMA_SEPARATED, (short)2, tables.DecimalFormatColumnRender.RIGHT));
            tblEarmark.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        btnSearch.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setBorderPainted(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSearch.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblSelected.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblSelected.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSelected.setText("0 Selected Transactions");

        chkAll.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        chkAll.setText("Check All");
        chkAll.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chkAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAllActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/earmark-cancel.png"))); // NOI18N
        btnCancel.setText("Cancel Earmark");
        btnCancel.setBorderPainted(false);
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/close.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.setBorderPainted(false);
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 360, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnSearch))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(chkAll))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(lblSelected))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(chkAll)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblSelected)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getRootPane().setDefaultButton(btnSearch);

        setBounds(0, 0, 592, 462);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        //javax.swing.JOptionPane.showConfirmDialog(this, "Mensahe");
        //javax.swing.JOptionPane.showMessageDialog(this, mex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
        reQueryForCancel();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void reQueryForCancel() {
        String sqlCmd =
                "SELECT " +
                    "earmrk_id, " +
                    "transact, " +
                    "total_amnt, " +
                    "particular " +
                "FROM " +
                    "buds.earmark_main " +
                "WHERE " +
                    (txtSearch.getText().trim().isEmpty() ? "" : "(earmrk_id LIKE ?) AND ") +
                    "(status = 0) " +
                "ORDER BY " +
                    "earmrk_id";
        try (budget.DBaseLink jdbc = new budget.DBaseLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement(sqlCmd)) {
            if (!txtSearch.getText().trim().isEmpty()) psmt.setString(1, "%" + txtSearch.getText() + "%");
            try (java.sql.ResultSet rst = psmt.executeQuery()) {
                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblEarmark.getModel();
                modelo.setRowCount(0);
                while (rst.next()) {
                    Object[] rowData = {
                        false,
                        rst.getString(1),
                        new java.text.SimpleDateFormat("MM/dd/yyyy").format(rst.getDate(2)),
                        rst.getDouble(3),
                        rst.getString(4)
                    };
                    modelo.addRow(rowData);
                }
            }

        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(VoidForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        reQueryForCancel();
        tblEarmark.getModel().addTableModelListener(tblModelListen);
    }//GEN-LAST:event_formInternalFrameOpened

    private void chkAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAllActionPerformed
        // TODO add your handling code here:
        tblEarmark.getModel().removeTableModelListener(tblModelListen);
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblEarmark.getModel();
        short count = 0;
        for (short abc = 0; abc < modelo.getRowCount(); abc++) {
            modelo.setValueAt(chkAll.isSelected(), abc, 0);
            count += (chkAll.isSelected() ? 1 : 0);
        }
        lblSelected.setText(count + " Selected Transactions");
        tblEarmark.getModel().addTableModelListener(tblModelListen);
    }//GEN-LAST:event_chkAllActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        String[] options = {"Yes", "No"};
        boolean verify = javax.swing.JOptionPane.showOptionDialog(
                this,
                "Are you sure to CANCEL the selected Earmark?", title,
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[options.length - 1]) == javax.swing.JOptionPane.NO_OPTION;
        if (verify) return;

        String sqlCmd =
                "UPDATE " +
                    "buds.earmark_main " +
                "SET " +
                    "status = 2 " +
                "WHERE " +
                    "(earmrk_id = ?)";
        try (budget.DBaseLink jdbc = new budget.DBaseLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement(sqlCmd)) {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblEarmark.getModel();
            for (short abc = 0; abc < modelo.getRowCount(); abc++) {
                boolean test = Boolean.parseBoolean(modelo.getValueAt(abc, 0).toString());
                if (!test) continue;
                
                String value = modelo.getValueAt(abc, 1).toString();
                psmt.setString(1, value);
                psmt.addBatch();
            }
            psmt.executeBatch();

        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            javax.swing.JOptionPane.showMessageDialog(this, ex.getNextException(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(VoidForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        doDefaultCloseAction();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JCheckBox chkAll;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelected;
    private javax.swing.JTable tblEarmark;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private final javax.swing.event.TableModelListener tblModelListen = new javax.swing.event.TableModelListener() {
        @Override
        public void tableChanged(javax.swing.event.TableModelEvent evt) {
            if (evt.getType() != javax.swing.event.TableModelEvent.UPDATE) return;

            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblEarmark.getModel();
            short count = 0;
            for (short abc = 0; abc < modelo.getRowCount(); abc++) {
                boolean checked = Boolean.parseBoolean(modelo.getValueAt(abc, 0).toString());
                count += (checked ? 1 : 0);
            }
            lblSelected.setText(count + " Selected Transactions");
            chkAll.setSelected(modelo.getRowCount() == count);
        }
    };
}
