package earmark.prep;

/**
 *
 * @author felix
 */
public class PrepareForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form EarmarkPrepareForm
     */
    public PrepareForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNew = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnClose2 = new javax.swing.JButton();
        pnlOpen = new javax.swing.JPanel();
        btnModify = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        btnElisan = new javax.swing.JButton();
        btnClose3 = new javax.swing.JButton();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        txtEarMark = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        txtBasis = new javax.swing.JTextField();
        txtFund = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        txtResp = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        calTrnDate = new com.toedter.calendar.JDateChooser();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        calExpire = new com.toedter.calendar.JDateChooser();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        txtDetail = new javax.swing.JTextArea();
        txtReqBy = new javax.swing.JTextField();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        tblTran = new javax.swing.JTable();
        javax.swing.JToolBar jToolBar1 = new javax.swing.JToolBar();
        btnAddFPP = new javax.swing.JButton();
        javax.swing.JToolBar.Separator jSeparator1 = new javax.swing.JToolBar.Separator();
        btnDelFPP = new javax.swing.JButton();
        fmtTotal = new javax.swing.JFormattedTextField();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        txtPrepBy = new javax.swing.JTextField();
        pnlMain = new javax.swing.JPanel();
        javax.swing.JButton btnNew = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        javax.swing.JButton btnClose = new javax.swing.JButton();

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/save.png"))); // NOI18N
        btnSave.setText("Post");
        btnSave.setBorderPainted(false);
        btnSave.setEnabled(false);
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setBorderPainted(false);
        btnCancel.setFocusable(false);
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/change.png"))); // NOI18N
        btnChange.setText("Change");
        btnChange.setToolTipText("Change Responsibility Center");
        btnChange.setBorderPainted(false);
        btnChange.setFocusable(false);
        btnChange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChange.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnChange.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/close.png"))); // NOI18N
        btnClose2.setText("Close");
        btnClose2.setBorderPainted(false);
        btnClose2.setFocusable(false);
        btnClose2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnClose2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNewLayout = new javax.swing.GroupLayout(pnlNew);
        pnlNew.setLayout(pnlNewLayout);
        pnlNewLayout.setHorizontalGroup(
            pnlNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewLayout.createSequentialGroup()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                .addComponent(btnClose2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlNewLayout.setVerticalGroup(
            pnlNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnClose2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/modify.png"))); // NOI18N
        btnModify.setText("Modify");
        btnModify.setBorderPainted(false);
        btnModify.setFocusable(false);
        btnModify.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModify.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnModify.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/back.png"))); // NOI18N
        btnUndo.setText("Back");
        btnUndo.setBorderPainted(false);
        btnUndo.setFocusable(false);
        btnUndo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUndo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnUndo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });

        btnElisan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/change.png"))); // NOI18N
        btnElisan.setText("Change");
        btnElisan.setBorderPainted(false);
        btnElisan.setEnabled(false);
        btnElisan.setFocusable(false);
        btnElisan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnElisan.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnElisan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnElisan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnClose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/close.png"))); // NOI18N
        btnClose3.setText("Close");
        btnClose3.setBorderPainted(false);
        btnClose3.setFocusable(false);
        btnClose3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnClose3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpenLayout = new javax.swing.GroupLayout(pnlOpen);
        pnlOpen.setLayout(pnlOpenLayout);
        pnlOpenLayout.setHorizontalGroup(
            pnlOpenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpenLayout.createSequentialGroup()
                .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnElisan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(btnClose3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlOpenLayout.setVerticalGroup(
            pnlOpenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModify, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnUndo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnClose3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnElisan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setTitle("Transaction: Earmark - Preparation");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("Earmark No.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, -1, -1));

        txtEarMark.setEditable(false);
        txtEarMark.setForeground(java.awt.Color.blue);
        jPanel1.add(txtEarMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 14, 125, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Legal Basis");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 41, -1, -1));

        txtBasis.setEditable(false);
        jPanel1.add(txtBasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 39, 400, -1));

        txtFund.setEditable(false);
        jPanel1.add(txtFund, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 64, 620, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Fund Account");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 66, -1, -1));

        txtResp.setEditable(false);
        jPanel1.add(txtResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 89, 620, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Resp. Center");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 91, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Tran. Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 16, -1, -1));

        calTrnDate.setDateFormatString("MM/dd/yyyy");
        calTrnDate.setEnabled(false);
        jPanel1.add(calTrnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 14, 100, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Expiry Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 41, -1, -1));

        calExpire.setDateFormatString("MM/dd/yyyy");
        calExpire.setEnabled(false);
        jPanel1.add(calExpire, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 39, 100, -1));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtDetail.setEditable(false);
        txtDetail.setColumns(20);
        txtDetail.setRows(3);
        jScrollPane1.setViewportView(txtDetail);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 114, 620, -1));

        txtReqBy.setEditable(false);
        txtReqBy.setDocument(new dbase.dcare.FixedSizePlainDocument(60));
        jPanel1.add(txtReqBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 168, 620, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Requested by");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("Particulars");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 116, -1, -1));

        lblStatus.setForeground(java.awt.Color.red);
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 14, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 746, 202));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblTran.setModel(MyTabModel);
        tblTran.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblTran.setEnabled(false);
        tblTran.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblTran);
        if (tblTran.getColumnModel().getColumnCount() > 0) {
            tblTran.getColumnModel().getColumn(0).setPreferredWidth(200);
            tblTran.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblTran.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblTran.getColumnModel().getColumn(2).setCellRenderer(new tables.LabelColumnRender(tables.LabelColumnRender.CENTER));
            tblTran.getColumnModel().getColumn(3).setPreferredWidth(110);
            tblTran.getColumnModel().getColumn(3).setCellRenderer(new tables.DecimalFormatColumnRender(tables.DecimalFormatColumnRender.COMMA_SEPARATED, (short)2, tables.DecimalFormatColumnRender.RIGHT));
            tblTran.getColumnModel().getColumn(4).setPreferredWidth(120);
            tblTran.getColumnModel().getColumn(4).setCellRenderer(new tables.DecimalFormatColumnRender(tables.DecimalFormatColumnRender.COMMA_SEPARATED, (short)2, tables.DecimalFormatColumnRender.RIGHT));
            tblTran.getColumnModel().getColumn(5).setMinWidth(0);
            tblTran.getColumnModel().getColumn(5).setPreferredWidth(0);
            tblTran.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnAddFPP.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnAddFPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/add_row.gif"))); // NOI18N
        btnAddFPP.setBorderPainted(false);
        btnAddFPP.setEnabled(false);
        btnAddFPP.setFocusable(false);
        btnAddFPP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddFPP.setOpaque(false);
        btnAddFPP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddFPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFPPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAddFPP);
        jToolBar1.add(jSeparator1);

        btnDelFPP.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnDelFPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/delete-row.png"))); // NOI18N
        btnDelFPP.setBorderPainted(false);
        btnDelFPP.setEnabled(false);
        btnDelFPP.setFocusable(false);
        btnDelFPP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelFPP.setOpaque(false);
        btnDelFPP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelFPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelFPPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDelFPP);

        fmtTotal.setEditable(false);
        fmtTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        fmtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fmtTotal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        fmtTotal.setValue(0D);

        jLabel9.setText("Total");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("Prepared by");

        txtPrepBy.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fmtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrepBy, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fmtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrepBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 232, 746, -1));

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/new.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.setBorderPainted(false);
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/open.png"))); // NOI18N
        btnOpen.setText("Open");
        btnOpen.setBorderPainted(false);
        btnOpen.setFocusable(false);
        btnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/close.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.setBorderPainted(false);
        btnClose.setFocusable(false);
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 482, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 474, 740, 50));

        setBounds(0, 0, 780, 568);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        if (!txtEarMark.getText().trim().isEmpty()) btnCancelActionPerformed(evt);

        earmark.prep.TransDialog dialogo = new earmark.prep.TransDialog();
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);

        if (!dialogo.isChoice()) {
            dialogo.dispose();
            return;
        }
        try {
            earmark.Opesina selNode = dialogo.getNapiliNode();
            java.util.Calendar caldate = java.util.Calendar.getInstance();
            caldate.setTime(new java.text.SimpleDateFormat("yyyy-MM-dd").parse(System.getProperty("PETSAH")));

            txtEarMark.setText("EA" + caldate.get(java.util.Calendar.YEAR) + "-######");
            calTrnDate.setDate(caldate.getTime());
            caldate.add(java.util.Calendar.DATE, 5);
            calExpire.setDate(caldate.getTime());

            LegalBasis = Integer.parseInt(dialogo.getLegalBasis()[0].toString());
            Fund = Short.parseShort(dialogo.getFunding()[0].toString());
            Office = selNode.getUID();

            txtBasis.setText(dialogo.getLegalBasis()[1].toString());
            txtFund.setText(dialogo.getFunding()[0] + " - " + dialogo.getFunding()[1]);
            txtResp.setText(selNode.getUID().substring(5) + " " + selNode.getNgalan());
            txtReqBy.setText(selNode.getRequest());
            dialogo.dispose();

            
            boolean switchOn = dialogo.isChoice();
            calExpire.setEnabled(switchOn);
            calTrnDate.setEnabled(switchOn);
            txtDetail.setEditable(switchOn);
            txtReqBy.setEditable(switchOn);
            btnAddFPP.setEnabled(switchOn);
            btnDelFPP.setEnabled(!switchOn);
            tblTran.setEnabled(switchOn);

            MyTabModel.setRowCount(0);

            pnlNew.setVisible(switchOn);
            pnlMain.setVisible(!switchOn);
                    
        } catch (java.text.ParseException | NumberFormatException mex) {
            javax.swing.JOptionPane.showMessageDialog(this, mex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, mex);
        } finally {
            
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        getContentPane().add(pnlNew,  new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 474, 740, 50));
        getContentPane().add(pnlOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 474, 740, 50));
        pnlNew.setVisible(false);
        pnlOpen.setVisible(false);
        
        txtPrepBy.setText(System.getProperty("USERNAME"));
        tblTran.getModel().addTableModelListener(new javax.swing.event.TableModelListener() {
            @Override
            public void tableChanged(javax.swing.event.TableModelEvent evt) {
                if (evt.getType() != javax.swing.event.TableModelEvent.UPDATE) return;
                
                double total = 0D;
                for (short abc = 0; abc < MyTabModel.getRowCount(); abc++) {
                    total += Double.parseDouble(MyTabModel.getValueAt(abc, 3).toString());
                }
                fmtTotal.setValue(total);
            }
        });
        tblTran.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                if (evt.getValueIsAdjusting()) return;
                btnDelFPP.setEnabled(tblTran.getSelectedRow() >= 0 & tblTran.isEnabled());
            }
        });
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        calTrnDate.setDate(null);
        calExpire.setDate(null);

        LegalBasis = null;
        Fund = null;
        Office = null;

        txtEarMark.setText("");
        txtBasis.setText("");
        txtFund.setText("");
        txtDetail.setText("");
        txtResp.setText("");
        txtReqBy.setText("");
        fmtTotal.setValue(0D);
        MyTabModel.setRowCount(0);
        lblStatus.setText("");

        boolean turnOff = false;
        pnlNew.setVisible(turnOff);
        pnlMain.setVisible(!turnOff);

        calExpire.setEnabled(turnOff);
        calTrnDate.setEnabled(turnOff);
        btnAddFPP.setEnabled(turnOff);
        btnDelFPP.setEnabled(turnOff);
        tblTran.setEnabled(turnOff);
        txtDetail.setEditable(turnOff);
        txtReqBy.setEditable(turnOff);
        

        pnlNew .setVisible(turnOff);
        pnlMain.setVisible(!turnOff);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddFPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFPPActionPerformed
        // TODO add your handling code here:
        earmark.prep.AddFPPDialog dialogo = new earmark.prep.AddFPPDialog(Office, CLASS_CODE);
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);

        if (!dialogo.isChoice()) {
            dialogo.dispose();
            return;
        }
        
        earmark.Classification leafNode = dialogo.getNapiliNode();
        Object[] rowData = {
            dialogo.getPPF()[1],
            leafNode.getTitulo(),
            leafNode.getUID(),
            0D,
            leafNode.getBalances(),
            dialogo.getPPF()[0]
        };
        MyTabModel.addRow(rowData);
        CLASS_CODE = leafNode.getRootID();
        
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnAddFPPActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        doDefaultCloseAction();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String sqlCmd0 =
                "INSERT INTO buds.earmark_main (" +
                    "earmrk_id, " +     // 1 - character
                    "years, " +         // 2 - smallint
                    "transact, " +      // 3 - date
                    "expiry, " +        // 4 - date
                    "legal_uid, " +     // 5 - integer
                    "fund_acct, " +     // 6 - smallint
                    "resp_cntr, " +     // 7 - character
                    "particular, " +    // 8 - character
                    "requested, " +     // 9 - character
                    "total_amnt, " +    //10 - double
                    "userid) " +        //11 - character
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
               sqlCmdS = 
                "INSERT INTO buds.earmark_sub (" +
                    "years, " +     // 1 - smallint
                    "earmrk_id, " + // 2 - character
                    "seq_order, " + // 3 - smallint
                    "ppf_uid, " +   // 4 - character
                    "acct_code, " + // 5 - character
                    "amount, " +    // 6 - double
                    "allot_bal, " + // 7 - double
                    "classes) " +   // 8 - double
                "VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
        try (budget.DBaseLink jdbc = new budget.DBaseLink();
                java.sql.PreparedStatement serial = jdbc.prepareStatement("SELECT NEXTVAL('buds.earmark_seq');")) {
            java.util.Calendar caldate = java.util.Calendar.getInstance();
            caldate.setTime(new java.text.SimpleDateFormat("yyyy-MM-dd").parse(System.getProperty("PETSAH")));
            short year = (short)caldate.get(java.util.Calendar.YEAR);
            String newEarmark;
            try (java.sql.ResultSet rst = serial.executeQuery()) {
                rst.next();
                newEarmark = txtEarMark.getText();
                newEarmark = newEarmark.substring(0, 6) + "-" + new java.text.DecimalFormat("000000").format(rst.getInt(1));
                txtEarMark.setText(newEarmark);
            }
            try(java.sql.PreparedStatement psmt0 = jdbc.prepareStatement(sqlCmd0);
                    java.sql.PreparedStatement psmt1 = jdbc.prepareStatement(sqlCmdS);) {
                jdbc.setAutoCommit(false);
                
                psmt0.setString(1,  newEarmark);
                psmt0.setShort (2,  year);
                psmt0.setDate  (3,  new java.sql.Date(calTrnDate.getDate().getTime()));
                psmt0.setDate  (4,  new java.sql.Date(calExpire.getDate().getTime()));
                psmt0.setInt   (5,  LegalBasis);
                psmt0.setShort (6,  Fund);
                psmt0.setString(7,  Office);
                psmt0.setString(8,  txtDetail.getText());
                psmt0.setString(9,  txtReqBy.getText());
                psmt0.setDouble(10, Double.parseDouble(fmtTotal.getValue().toString()));
                psmt0.setString(11, System.getProperty("USERID"));
                psmt0.executeUpdate();
                
                
                for (short abc = 0; abc < MyTabModel.getRowCount(); abc++) {
                    psmt1.setShort (1, year);
                    psmt1.setString(2, newEarmark);
                    psmt1.setShort (3, (short)(abc + 1));
                    psmt1.setString(4, MyTabModel.getValueAt(abc, 5).toString());
                    psmt1.setString(5, MyTabModel.getValueAt(abc, 2).toString());
                    long value = Math.round(((Double)MyTabModel.getValueAt(abc, 3)) * 100D);
                    psmt1.setDouble(6, value * 0.01D);
                    value = Math.round(((Double)MyTabModel.getValueAt(abc, 4)) * 100D);
                    psmt1.setDouble(7,  value * 0.01D);
                    psmt1.setShort (8,  Short.parseShort(CLASS_CODE, 10));
                    psmt1.addBatch();
                }
                psmt1.executeBatch();
                jdbc.commit();
                
                //if (lblStatus.getText().isEmpty()) lblStatus.setText("For Approval");

                javax.swing.JOptionPane.showMessageDialog(this, "Record saved successfully.", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);
                pnlNew.setVisible(false);
                pnlMain.setVisible(true);

                boolean switchOn = false;
                calExpire.setEnabled(switchOn);
                calTrnDate.setEnabled(switchOn);
                txtDetail.setEditable(switchOn);
                txtReqBy.setEditable(switchOn);
                btnAddFPP.setEnabled(switchOn);
                btnDelFPP.setEnabled(switchOn);
                tblTran.setEnabled(switchOn);
                btnUndo.setEnabled(switchOn);
                btnElisan.setEnabled(switchOn);
                

                
            } catch (java.sql.SQLException ex) {
                jdbc.rollback();
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDelFPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelFPPActionPerformed
        // TODO add your handling code here:
        int selrow = tblTran.getSelectedRow(), rowIhap = 0;
        
        selrow = tblTran.convertRowIndexToModel(selrow);
        String sqlCmdM =
                "DELETE FROM " +
                    "buds.earmark_main " +
                "WHERE " +
                    "(earmrk_id = ?)",
               sqlCmdS = 
                "DELETE FROM " +
                    "buds.earmark_sub " +
                "WHERE " +
                    "(earmrk_id = ?) AND " +
                    "(ppf_uid   = ?) AND " +
                    "(acct_code = ?)",
               earMark = txtEarMark.getText(),
               accnts  = MyTabModel.getValueAt(selrow, 2).toString(),
               ppfIDs  = MyTabModel.getValueAt(selrow, 5).toString();
        try (budget.DBaseLink jdbc = new budget.DBaseLink();
                java.sql.PreparedStatement psmtm = jdbc.prepareStatement(sqlCmdM);
                java.sql.PreparedStatement psmts = jdbc.prepareStatement(sqlCmdS)) {
            jdbc.setAutoCommit(false);
            try {
                psmts.setString(1, earMark);
                psmts.setString(2, ppfIDs);
                psmts.setString(3, accnts);
                psmts.executeUpdate();

                psmtm.setString(1, earMark);
                if (rowIhap == 1) psmtm.executeUpdate();
                jdbc.commit();

                MyTabModel.removeRow(selrow);
                btnDelFPP.setEnabled(MyTabModel.getRowCount() > 0);
                javax.swing.JOptionPane.showMessageDialog(this, "Record remove successfully.", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);
                if (MyTabModel.getRowCount() == 0) CLASS_CODE = null;


            } catch (java.sql.SQLException ex) {
                jdbc.rollback();
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_btnDelFPPActionPerformed

    private void otrogQuery() {
        String sqlCmdM =
                "SELECT " +
                    "earmark_main.transact, " +     // 1
                    "earmark_main.expiry, " +       // 2
                    "earmark_main.legal_uid, " +    // 3
                    "ordinances.legal_desc, " +     // 4
                    "earmark_main.fund_acct, " +    // 5
                    "funds.description, " +         // 6
                    "earmark_main.resp_cntr, " +    // 7
                    "offices.resp_id, " +           // 8
                    "offices.resp_sub, " +          // 9
                    "offices.description, " +       //10
                    "earmark_main.particular, " +   //11
                    "earmark_main.requested, " +    //12
                    "earmark_main.total_amnt, " +   //13
                    "earmark_main.status " +        //14
                "FROM " +
                    "buds.earmark_main JOIN buds.ordinances " +
                    "ON earmark_main.legal_uid = ordinances.legal_uid " +
                    "JOIN buds.fund_control funds " +
                    "ON earmark_main.years = funds.years " +
                    "AND earmark_main.fund_acct = funds.funds_id " +
                    "JOIN buds.fund_control offices " +
                    "ON earmark_main.years = offices.years " +
                    "AND earmark_main.resp_cntr = offices.centre_uid " +
                "WHERE " +
                    "(earmark_main.earmrk_id = ?) AND " +
                    "(funds.funds_id <> 0) AND (funds.services = 0)",
               sqlCmdS = 
                "SELECT " +
                    "fund_control.description, " +      // 1
                    "accounts.titles, " +               // 2
                    "accounts.coding, " +               // 3
                    "earmark_sub.amount, " +            // 4
                    "earmark_sub.allot_bal, " +         // 5
                    "earmark_sub.ppf_uid " +            // 6
                "FROM " +
                    "buds.earmark_sub JOIN buds.fund_control " +
                    "ON earmark_sub.years = fund_control.years " +
                    "AND earmark_sub.ppf_uid = fund_control.centre_uid " +
                    "JOIN acct.accounts " +
                    "ON earmark_sub.acct_code = accounts.coding " +
                "WHERE " +
                    "(earmark_sub.earmrk_id = ?) " +
                "ORDER BY " +
                    "earmark_sub.seq_order",
               earMark = txtEarMark.getText();
        try (budget.DBaseLink jdbc = new budget.DBaseLink();
                java.sql.PreparedStatement psmtm = jdbc.prepareStatement(sqlCmdM);
                java.sql.PreparedStatement psmts = jdbc.prepareStatement(sqlCmdS)) {
            
            psmtm.setString(1, earMark);
            try (java.sql.ResultSet rst = psmtm.executeQuery()) {
                rst.next();
                calTrnDate.setDate(rst.getDate(1));
                calExpire.setDate(rst.getDate(2));
                LegalBasis = rst.getInt(3);
                txtBasis.setText(rst.getString(4));
                Fund = rst.getShort(5);
                txtFund.setText(rst.getShort(5) + " - " + rst.getString(6));
                Office = rst.getString(7);
                txtResp.setText(rst.getShort(8) + "-" + rst.getShort(9) + " " + rst.getString(10));
                txtDetail.setText(rst.getString(11));
                txtReqBy.setText(rst.getString(12));
                fmtTotal.setValue(rst.getDouble(13));
                lblStatus.setText(rst.getShort(14) == 1 ? "Obligated" : (rst.getShort(14) == 2 ? "Cancelled/Expired" : ""));
                //javax.swing.JOptionPane.showMessageDialog(this, "Record remove successfully.", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            psmts.setString(1, earMark);
            try (java.sql.ResultSet tbl = psmts.executeQuery()) {
                MyTabModel.setRowCount(0);
                while (tbl.next()) {
                    Object[] rowData = {
                        tbl.getString(1),
                        tbl.getString(2),
                        tbl.getString(3),
                        tbl.getDouble(4),
                        tbl.getDouble(5),
                        tbl.getString(6)
                    };
                    MyTabModel.addRow(rowData);
                }
            }


        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }
    
    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        boolean switchOn = evt.getActionCommand().equals("Modify");
        calExpire.setEnabled(switchOn);
        calTrnDate.setEnabled(switchOn);
        txtDetail.setEditable(switchOn);
        txtReqBy.setEditable(switchOn);
        btnAddFPP.setEnabled(switchOn);
        //btnDelFPP.setEnabled(switchOn);
        tblTran.setEnabled(switchOn);
        btnUndo.setEnabled(switchOn);
        btnElisan.setEnabled(switchOn);

        if (switchOn) {
            btnModify.setText("Update");
            btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/update.png"))); // NOI18N
            btnUndo.setText("Undo");
            btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/undo.png"))); // NOI18N
        } else {
            UpdateEarmark();
            btnModify.setText("Modify");
            btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/modify.png"))); // NOI18N
            btnUndo.setText("Back");
            btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/back.png"))); // NOI18N
        }
    }//GEN-LAST:event_btnModifyActionPerformed
    
    private void UpdateEarmark() {
        String
            sqlCmdM =
                "UPDATE " +
                    "buds.earmark_main " +
                "SET " +
                    "transact   = ?, " + // 1 - date
                    "expiry     = ?, " + // 2 - date
                    "legal_uid  = ?, " + // 3 - integer
                    "fund_acct  = ?, " + // 4 - smallint
                    "resp_cntr  = ?, " + // 5 - character
                    "particular = ?, " + // 6 - character
                    "requested  = ?, " + // 7 - character
                    "total_amnt = ?, " + // 8 - double
                    "userid     = ?  " + // 9 - character
                "WHERE " +
                    "(earmrk_id = ?)",   //10
            sqlCmdS = 
                "UPDATE " +
                    "buds.earmark_sub " +
                "SET " +
                    "seq_order = ?, " +         // 1 - smallint
                    "amount    = ?, " +         // 2 - double
                    "allot_bal = ? " +          // 3 - double
                "WHERE " +
                    "(earmrk_id = ?) AND " +    // 4
                    "(ppf_uid   = ?) AND " +    // 5
                    "(acct_code = ?)",          // 6
            sqlCmdI = 
                "INSERT INTO buds.earmark_sub (" +
                    "years, " +         // 1
                    "earmrk_id, " +     // 2
                    "seq_order, " +     // 3
                    "ppf_uid, " +       // 4
                    "acct_code, " +     // 5
                    "amount, " +        // 6
                    "allot_bal) " +     // 7
                "VALUES " +
                    "(?, ?, ?, ?, ?, ?, ?)";
        try (budget.DBaseLink jdbc = new budget.DBaseLink();
                java.sql.PreparedStatement serial = jdbc.prepareStatement("SELECT NEXTVAL('buds.earmark_seq');")) {
            String newEarmark = txtEarMark.getText();
            java.util.Calendar caldate = java.util.Calendar.getInstance();
            caldate.setTime(new java.text.SimpleDateFormat("yyyy-MM-dd").parse(System.getProperty("PETSAH")));
            short year = (short)caldate.get(java.util.Calendar.YEAR);

            try(java.sql.PreparedStatement pstm = jdbc.prepareStatement(sqlCmdM);
                    java.sql.PreparedStatement psts = jdbc.prepareStatement(sqlCmdS);
                    java.sql.PreparedStatement psti = jdbc.prepareStatement(sqlCmdI)) {
                jdbc.setAutoCommit(false);
                pstm.setDate  ( 1,  new java.sql.Date(calTrnDate.getDate().getTime()));
                pstm.setDate  ( 2,  new java.sql.Date(calExpire.getDate().getTime()));
                pstm.setInt   ( 3,  LegalBasis);
                pstm.setShort ( 4,  Fund);
                pstm.setString( 5,  Office);
                pstm.setString( 6,  txtDetail.getText());
                pstm.setString( 7,  txtReqBy.getText());
                pstm.setDouble( 8,  Double.parseDouble(fmtTotal.getValue().toString()));
                pstm.setString( 9,  System.getProperty("USERID"));
                /***************************************************************/
                pstm.setString(10, newEarmark);
                pstm.executeUpdate();
                
                for (short abc = 0; abc < MyTabModel.getRowCount(); abc++) {
                    psts.setShort (1,  (short)(abc + 1));
                    long value = Math.round(((Double)MyTabModel.getValueAt(abc, 3)) * 100D);
                    psts.setDouble(2,  value * 0.01D);
                    value = Math.round(((Double)MyTabModel.getValueAt(abc, 4)) * 100D);
                    psts.setDouble(3,  value * 0.01D);
                    /***********************************************************/
                    psts.setString(4,  newEarmark);
                    psts.setString(5,  MyTabModel.getValueAt(abc, 5).toString());
                    psts.setString(6,  MyTabModel.getValueAt(abc, 2).toString());
                    if (psts.executeUpdate() == 0) {
                        psti.setShort (1, year);
                        psti.setString(2, newEarmark);
                        psti.setShort (3, (short)(abc + 1));
                        psti.setString(4, MyTabModel.getValueAt(abc, 5).toString());
                        psti.setString(5, MyTabModel.getValueAt(abc, 2).toString());
                        value = Math.round(((Double)MyTabModel.getValueAt(abc, 3)) * 100D);
                        psti.setDouble(6,  value * 0.01D);
                        value = Math.round(((Double)MyTabModel.getValueAt(abc, 4)) * 100D);
                        psti.setDouble(7,  value * 0.01D);
                        psti.executeUpdate();
                    }
                }
                jdbc.commit();
                
                if (lblStatus.getText().isEmpty()) lblStatus.setText("For Approval");

                javax.swing.JOptionPane.showMessageDialog(this, "Record saved successfully.", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);
                pnlOpen.setVisible(false);
                pnlMain.setVisible(true);


            } catch (java.sql.SQLException ex) {
                jdbc.rollback();
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(PrepareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals("Undo")) {
            boolean switchOn = false;
            calExpire.setEnabled(switchOn);
            calTrnDate.setEnabled(switchOn);
            txtDetail.setEditable(switchOn);
            txtReqBy.setEditable(switchOn);
            btnAddFPP.setEnabled(switchOn);
            btnDelFPP.setEnabled(switchOn);
            tblTran.setEnabled(switchOn);
            btnElisan.setEnabled(switchOn);
            
            btnUndo.setText("Back");
            btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/back.png"))); // NOI18N
            btnModify.setText("Modify");
            btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imahen/modify.png"))); // NOI18N

        } else {
            calTrnDate.setDate(null);
            calExpire.setDate(null);

            calExpire.setEnabled(false);
            calTrnDate.setEnabled(false);
            LegalBasis = null;
            Fund = null;
            Office = null;

            txtEarMark.setText("");
            txtBasis.setText("");
            txtFund.setText("");
            txtDetail.setText("");
            txtResp.setText("");
            txtReqBy.setText("");
            fmtTotal.setValue(0D);

            pnlNew.setVisible(false);
            pnlMain.setVisible(true);

            btnAddFPP.setEnabled(false);
            btnDelFPP.setEnabled(false);
            tblTran.setEnabled(false);

            MyTabModel.setRowCount(0);
            lblStatus.setText("");
            
            pnlOpen.setVisible(false);
            pnlMain.setVisible(true);
        }
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        OpenDialog dialogo = new OpenDialog();
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);

        if (!dialogo.isChoice()) return;

        txtEarMark.setText(dialogo.getEarMark());
        otrogQuery();

        btnModify.setEnabled(lblStatus.getText().equals("For Approval"));
        pnlOpen.setVisible(true);
        pnlMain.setVisible(false);
    }//GEN-LAST:event_btnOpenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFPP;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnClose2;
    private javax.swing.JButton btnClose3;
    private javax.swing.JButton btnDelFPP;
    private javax.swing.JButton btnElisan;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUndo;
    private com.toedter.calendar.JDateChooser calExpire;
    private com.toedter.calendar.JDateChooser calTrnDate;
    private javax.swing.JFormattedTextField fmtTotal;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlNew;
    private javax.swing.JPanel pnlOpen;
    private javax.swing.JTable tblTran;
    private javax.swing.JTextField txtBasis;
    private javax.swing.JTextArea txtDetail;
    private javax.swing.JTextField txtEarMark;
    private javax.swing.JTextField txtFund;
    private javax.swing.JTextField txtPrepBy;
    private javax.swing.JTextField txtReqBy;
    private javax.swing.JTextField txtResp;
    // End of variables declaration//GEN-END:variables

    private Integer LegalBasis;
    private Short   Fund;
    private String  Office;

    private String  CLASS_CODE = "";

    private final javax.swing.table.DefaultTableModel MyTabModel = new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{
                "FPP", "Account Title", "Acct Code", "Amount", "ALLOT. BAL.", "ppf_id"
                /* 0 ,  1,               2,           3,        4,             5    */
            }
    ) {
        Class[] types = new Class[]{
            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
        };
        boolean[] canEdit = new boolean[]{
            false, false, false, true, false, false
        };

        @Override
        public Class getColumnClass(int columnIndex) {
            return types[columnIndex];
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }

        @Override
        public void setValueAt(Object aValue, int row, int col) {
            switch (col) {
                case 3:
                    double amount = (Double)aValue,
                           allots = (Double) getValueAt(row, 4),
                           oldval = (Double) getValueAt(row, col);
                    if (amount > allots) {
                        classes.MsgBox.showWarning(PrepareForm.this, "Amount exceeded from balance.", title);
                        aValue = oldval;
                    }
            }
            super.setValueAt(aValue, row, col);
        }
    };
}
